[tools]
"github:github/copilot-cli" = "latest"
java = "temurin-25"
node = "24"
maven = "3.9.9"
quarkus = "3.38.3"
ggshield = "latest"
git-cliff = "latest"

[tasks.clean_dev]
run = "podman compose down -v && podman volume prune && podman compose up -d"
interactive = true

[tasks.dev]
run = "podman compose up -d"

[env]
MAIL_ADMIN="admin@localhost"
