quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.username=${DB_USER:festival}
%dev.quarkus.datasource.password=${DB_PASSWORD:festival}
%dev.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/festival}

%prod.quarkus.datasource.username=${DB_USER:festival}
%prod.quarkus.datasource.password=${DB_PASSWORD:festival}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/festival}
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

%test.quarkus.datasource.devservices.enabled=true

planning.solver.seconds-limit=120
planning.solver.unimproved-seconds-limit=30
%test.planning.solver.seconds-limit=3
%test.planning.solver.unimproved-seconds-limit=2

quarkus.http.port=${HTTP_PORT:8080}
