quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.username=${DB_USER:festival}
%dev.quarkus.datasource.password=${DB_PASSWORD:festival}
%dev.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/festival}

%prod.quarkus.datasource.username=${DB_USER:festival}
%prod.quarkus.datasource.password=${DB_PASSWORD:festival}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/festival}
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:planning-equipes-test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa

planning.solver.seconds-limit=180
planning.solver.unimproved-seconds-limit=60
%test.planning.solver.seconds-limit=3
%test.planning.solver.unimproved-seconds-limit=2

quarkus.http.port=${HTTP_PORT:8080}
