package dev.sylvain.planning.api;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.nullValue;

import dev.sylvain.planning.service.EditionContext;
import dev.sylvain.planning.service.referentiel.ReferenceDataService;
import dev.sylvain.planning.service.solve.SolveBudget;
import dev.sylvain.planning.service.solve.SolveBudgetPolicy;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

/**
 * The edition's solve budget over HTTP: stored per edition, bounded by the
 * operator's ceiling — the default one of {@code application.properties},
 * 3600 s for both halves — and refused rather than trimmed above it.
 */
@QuarkusTest
class SolverBudgetResourceTest {

    private static final String HEADER = "X-Edition-Id";
    /** The editions a test created, ids generated by the server. */
    private final java.util.List<String> created = new java.util.ArrayList<>();

    @Inject
    SolveBudgetPolicy policy;

    @Inject
    ReferenceDataService referenceData;

    @Inject
    EditionContext editionContext;

    @AfterEach
    void dropTheEditions() {
        created.forEach(id -> given().when().delete("/api/editions/" + id));
        created.clear();
    }

    @Test
    void theSettingsCarryTheInstanceDefaultsAndCeilings() {
        String first = createEdition("Budget first");
        given().header(HEADER, first)
                .when()
                .get("/api/parametres-solveur")
                .then()
                .statusCode(200)
                .body("dureeResolutionSecondes", nullValue())
                .body("plateauSecondes", nullValue())
                .body("instance.defaultSecondsLimit", equalTo(3))
                .body("instance.defaultPlateauSeconds", equalTo(2))
                .body("instance.maxSecondsLimit", equalTo(3600))
                .body("instance.maxPlateauSeconds", equalTo(3600));
    }

    @Test
    void twoEditionsEachRunTheirOwnBudget() {
        String first = createEdition("Budget first");
        String second = createEdition("Budget second");
        save(first, "{\"dureeResolutionSecondes\":1200,\"plateauSecondes\":60}", 200);
        save(second, "{\"dureeResolutionSecondes\":600,\"plateauSecondes\":0}", 200);

        assertThat(budgetOf(first)).isEqualTo(new SolveBudget(1200L, 60L, null));
        assertThat(budgetOf(second)).isEqualTo(new SolveBudget(600L, 0L, null));

        // « Revenir au défaut »: both halves back to the instance's.
        save(first, "{\"dureeResolutionSecondes\":null,\"plateauSecondes\":null}", 200);
        assertThat(budgetOf(first)).isEqualTo(new SolveBudget(3L, 2L, null));
        assertThat(budgetOf(second)).isEqualTo(new SolveBudget(600L, 0L, null));
    }

    @Test
    void aBudgetAboveTheCeilingIsRefusedCitingIt() {
        String first = createEdition("Budget first");
        given().header(HEADER, first)
                .contentType("application/json")
                .body("{\"dureeResolutionSecondes\":7200}")
                .when()
                .put("/api/parametres-solveur")
                .then()
                .statusCode(400)
                .body("message", containsString("au plus 1 h"));
        save(first, "{\"dureeResolutionSecondes\":600,\"plateauSecondes\":900}", 400);
    }

    /**
     * A scenario file carrying a budget above this instance's ceiling imports:
     * the value is stored as the file says and every launch runs it capped,
     * with the warning — the ADR 0051 treatment of a value stored earlier.
     */
    @Test
    void aScenarioBudgetAboveTheCeilingImportsAndRunsCapped() {
        String first = createEdition("Budget first");
        importScenario(first, 7200);

        given().header(HEADER, first)
                .when()
                .get("/api/parametres-solveur")
                .then()
                .statusCode(200)
                .body("dureeResolutionSecondes", equalTo(7200));
        SolveBudget budget = budgetOf(first);
        assertThat(budget.secondsLimit()).isEqualTo(3600L);
        assertThat(budget.warning()).contains("2 h").contains("1 h");
    }

    /**
     * The mail switch sends the stored budget back whole (the Paramètres
     * page): a duration above a ceiling lowered since must not make it fail.
     * Changing that duration, though, is a value entered now.
     */
    @Test
    void theMailSwitchSavesOverAStoredDurationAboveTheCeiling() {
        String first = createEdition("Budget first");
        importScenario(first, 7200);

        save(first, "{\"dureeResolutionSecondes\":7200,\"plateauSecondes\":null,\"mailFinResolution\":true}", 200);
        given().header(HEADER, first)
                .when()
                .get("/api/parametres-solveur")
                .then()
                .statusCode(200)
                .body("dureeResolutionSecondes", equalTo(7200))
                .body("mailFinResolution", equalTo(true));
        // A plateau changed on its own saves too.
        save(first, "{\"dureeResolutionSecondes\":7200,\"plateauSecondes\":600,\"mailFinResolution\":true}", 200);
        save(first, "{\"dureeResolutionSecondes\":5400,\"plateauSecondes\":600,\"mailFinResolution\":true}", 400);
    }

    @Test
    void aLaunchAskingAboveTheCeilingIsRefusedBeforeAnyJobExists() {
        String first = createEdition("Budget first");
        given().header(HEADER, first)
                .when()
                .post("/api/solve/async/reference-data?seconds=7200")
                .then()
                .statusCode(400)
                .body("message", containsString("au plus 1 h"));
        given().header(HEADER, first)
                .contentType("application/json")
                .body("{}")
                .when()
                .post("/api/solve/incremental/async?seconds=7200")
                .then()
                .statusCode(400)
                .body("message", containsString("au plus 1 h"));
    }

    private SolveBudget budgetOf(String edition) {
        return editionContext.executeIn(edition, () -> policy.forSolve(null, referenceData.getParametresSolveur()));
    }

    /** A scenario of one timeslot, one stand, one animateur, pinning {@code secondes} as its duration. */
    private static void importScenario(String edition, int secondes) {
        given().header(HEADER, edition)
                .contentType("text/plain")
                .body("""
                        parametresSolveur:
                          dureeResolutionSecondes: %d

                        festival:
                          dateDebut: 2026-07-08

                        creneaux:
                          - id: J1-MATIN
                            jour: 1
                            date: 2026-07-08
                            heureDebut: "09:00"
                            heureFin: "13:00"

                        stands:
                          - id: STAND-A
                            nom: Stand A
                            typologiesProposees:
                              - STRATEGIE
                            effectifMin: 1
                            effectifMax: 1
                            reserveMajeurs: false

                        animateurs:
                          - id: A1
                            prenom: Alice
                            nom: Budget
                            dateNaissance: 2002-07-19
                            manager: false
                            competences:
                              STRATEGIE: REFERENT
                            joursIndisponibles: []
                        """.formatted(secondes))
                .when()
                .post("/api/reference-data/import-scenario-fichier")
                .then()
                .statusCode(200);
    }

    private static void save(String edition, String body, int status) {
        given().header(HEADER, edition)
                .contentType("application/json")
                .body(body)
                .when()
                .put("/api/parametres-solveur")
                .then()
                .statusCode(status);
    }

    private String createEdition(String nom) {
        String id = given().contentType("application/json")
                .body("{\"nom\":\"" + nom + "\"}")
                .when()
                .post("/api/editions")
                .then()
                .statusCode(200)
                .extract()
                .path("id");
        created.add(id);
        return id;
    }
}
