package dev.sylvain.planning.api;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import dev.sylvain.planning.domain.ConstraintToggle;
import dev.sylvain.planning.domain.PlanningEvenement;
import dev.sylvain.planning.service.EditionContext;
import dev.sylvain.planning.service.analyse.Dosage;
import dev.sylvain.planning.service.analyse.KpiHistoriqueService;
import dev.sylvain.planning.service.analyse.PlanningKpiService;
import dev.sylvain.planning.service.analyse.WeightHistoryService;
import dev.sylvain.planning.service.referentiel.ReferenceDataService;
import dev.sylvain.planning.service.referentiel.WeightChange;
import dev.sylvain.planning.service.referentiel.WeightChangeOrigin;
import dev.sylvain.planning.service.solve.PlanDosageRepository;
import dev.sylvain.planning.service.solve.PlanningPersistenceService;
import dev.sylvain.planning.service.solve.PlanningService;
import dev.sylvain.planning.service.solve.Reamorcage;
import dev.sylvain.planning.service.solve.SolvePipeline;
import dev.sylvain.planning.service.solve.SolverJobService;
import dev.sylvain.planning.service.solve.SolverScoreTrace;
import dev.sylvain.planning.solver.ConstraintCatalog;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.path.json.JsonPath;
import jakarta.inject.Inject;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

/**
 * The weight history of an edition: a line per effective change, values
 * included, typed origin, scoped to the edition — and the dosage each solve
 * was launched under, stored with its KPI line.
 */
@QuarkusTest
class WeightHistoryResourceTest {

    private static final String HEADER = "X-Edition-Id";
    /** The editions a test created, ids generated by the server. */
    private final List<String> created = new java.util.ArrayList<>();

    /** first rule the deployment leaves at 1 and the catalogue ships active. */
    private static final String RULE = ConstraintCatalog.definitions().stream()
            .filter(ConstraintCatalog.ConstraintDefinition::dosable)
            .filter(ConstraintCatalog.ConstraintDefinition::activeByDefault)
            .filter(definition -> !"appreciationIncompatible".equals(definition.name())
                    && !"maxJoursConsecutifsTravailles".equals(definition.name()))
            .map(ConstraintCatalog.ConstraintDefinition::name)
            .findFirst()
            .orElseThrow();

    @Inject
    WeightHistoryService weightHistory;

    @Inject
    ReferenceDataService referenceData;

    @Inject
    EditionContext editionContext;

    @Inject
    SolverJobService solverJobs;

    @Inject
    SolverScoreTrace scoreTrace;

    @Inject
    KpiHistoriqueService kpiHistory;

    @Inject
    PlanningService planningService;

    @Inject
    SolvePipeline solvePipeline;

    @Inject
    PlanningPersistenceService persistence;

    @Inject
    PlanDosageRepository planDosage;

    @AfterEach
    void dropTheEditions() {
        await().atMost(Duration.ofSeconds(60))
                .until(() -> solverJobs.findActive().isEmpty());
        for (String edition : created.reversed()) {
            given().when().delete("/api/editions/" + edition);
        }
        created.clear();
    }

    @Test
    void aWeightChangeWritesItsEffectiveValuesAndTheSameValueWritesNothing() {
        String first = createEdition("Historique first");
        setWeight(first, "20");
        setWeight(first, "20");
        setWeight(first, "null");

        List<WeightChange> changes = changesOf(first);
        assertThat(changes).hasSize(2);
        assertThat(changes.get(0))
                .extracting(
                        WeightChange::weightBefore,
                        WeightChange::weightAfter,
                        WeightChange::backToDefault,
                        WeightChange::origin)
                .containsExactly(1, 20, false, WeightChangeOrigin.SCREEN);
        // « 20 → défaut (1) »
        assertThat(changes.get(1))
                .extracting(WeightChange::weightBefore, WeightChange::weightAfter, WeightChange::backToDefault)
                .containsExactly(20, 1, true);
        assertThat(changes.get(0).createdAt()).isNotNull();
    }

    @Test
    void aToggleWritesItsStatesAndAssistantWritesAreTyped() {
        String first = createEdition("Historique first");
        given().header(HEADER, first)
                .contentType("application/json")
                .body("{\"actif\":false}")
                .when()
                .put("/api/constraints/" + RULE)
                .then()
                .statusCode(200);
        given().header(HEADER, first)
                .contentType("application/json")
                .body("{\"actif\":false}")
                .when()
                .put("/api/constraints/" + RULE)
                .then()
                .statusCode(200);
        editionContext.executeIn(first, () -> referenceData.setConstraintWeight(RULE, 7, WeightChangeOrigin.ASSISTANT));

        List<WeightChange> changes = changesOf(first);
        assertThat(changes).hasSize(2);
        assertThat(changes.get(0))
                .extracting(WeightChange::activeBefore, WeightChange::activeAfter, WeightChange::weightAfter)
                .containsExactly(true, false, null);
        assertThat(changes.get(1).origin()).isEqualTo(WeightChangeOrigin.ASSISTANT);
        assertThat(changes.get(1).actor().name()).isEqualTo("ASSISTANT");
    }

    @Test
    void theHistoryIsScopedToItsEditionAndServedOverHttp() {
        String first = createEdition("Historique first");
        String second = createEdition("Historique second");
        setWeight(first, "9");

        assertThat(changesOf(second)).isEmpty();
        JsonPath history = given().header(HEADER, first)
                .when()
                .get("/api/constraints/" + RULE + "/historique")
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
        assertThat(history.getList("changes")).hasSize(1);
        assertThat(history.getString("changes[0].origin")).isEqualTo("SCREEN");
        assertThat(history.getInt("changes[0].weightAfter")).isEqualTo(9);
        given().header(HEADER, second)
                .when()
                .get("/api/constraints/historique")
                .then()
                .statusCode(200)
                .extract()
                .jsonPath()
                .getList("changes")
                .isEmpty();
    }

    @Test
    void aScenarioThatPinsItsDosageWritesOneLinePerRuleItChanges() {
        String first = createEdition("Historique first");
        importScenario(first);

        List<WeightChange> scenario =
                editionContext.executeIn(first, () -> weightHistory.all().changes());
        assertThat(scenario)
                .extracting(WeightChange::name)
                .containsExactlyInAnyOrder("appreciationIncompatible", "maxJoursConsecutifsTravailles");
        assertThat(scenario).allMatch(change -> change.origin() == WeightChangeOrigin.SCENARIO);

        // Imported again: nothing moves, nothing is written.
        importScenario(first);
        assertThat(editionContext.executeIn(first, () -> weightHistory.all().changes()))
                .hasSize(2);
    }

    @Test
    void aDuplicatedEditionStartsWithTheDosageItInherited() {
        String first = createEdition("Historique first");
        setWeight(first, "4");
        setWeight(first, "6");
        String copy = given().contentType("application/json")
                .body("{\"nom\":\"Copie du dosage\"}")
                .when()
                .post("/api/editions/" + first + "/dupliquer")
                .then()
                .statusCode(200)
                .extract()
                .path("id");
        created.add(copy);

        List<WeightChange> inherited = changesOf(copy);
        assertThat(inherited).singleElement().satisfies(change -> {
            assertThat(change.origin()).isEqualTo(WeightChangeOrigin.DUPLICATION);
            assertThat(change.sourceEdition()).isEqualTo(first);
            assertThat(change.weightBefore()).isEqualTo(1);
            assertThat(change.weightAfter()).isEqualTo(6);
        });
    }

    /**
     * The dosage is the solve's own, taken at launch: a weight changed while
     * the solver runs reaches the next solve, never the line of this one.
     */
    @Test
    void theDosageOfASolveIsTheOneItWasLaunchedUnder() {
        // The Autopsie outlives its editions, and a rerun reuses the id:
        // only the lines written from here on belong to this test.
        java.time.Instant start = java.time.Instant.now();
        String first = createEdition("Historique first");
        importScenario(first);
        setWeight(first, "5");
        String jobId = editionContext.executeIn(
                first,
                () -> solverJobs
                        .submitSolveFromReferenceData(4L, false, Reamorcage.AUCUN)
                        .getId());
        // follow() is called once the solver is built — after the dosage was taken.
        await().atMost(Duration.ofSeconds(60)).until(() -> {
            SolverScoreTrace.Trace trace = scoreTrace.snapshot();
            return trace != null && jobId.equals(trace.jobId());
        });
        setWeight(first, "8");
        await().atMost(Duration.ofSeconds(60))
                .until(() -> solverJobs.find(jobId).orElseThrow().isFinished());

        PlanningKpiService.PlanningKpi kpi = kpiHistory.list().stream()
                .filter(entry ->
                        first.equals(entry.editionId()) && entry.creeLe().isAfter(start))
                .findFirst()
                .orElseThrow()
                .kpi();
        Dosage dosage = kpi.dosage();
        assertThat(dosage).isNotNull();
        assertThat(dosage.weights())
                .containsEntry(RULE, 5)
                .containsEntry("appreciationIncompatible", 3)
                .containsEntry("maxJoursConsecutifsTravailles", 5);
        assertThat(dosage.isDefault()).isFalse();

        WeightHistoryService.ConstraintHistory history =
                editionContext.executeIn(first, () -> weightHistory.forConstraint(RULE));
        assertThat(history.resolutions())
                .filteredOn(resolution -> resolution.createdAt().isAfter(start))
                .singleElement()
                .satisfies(resolution -> {
                    assertThat(resolution.dosage().weights()).containsEntry(RULE, 5);
                    assertThat(resolution.score()).isNotNull();
                });
    }

    /**
     * The dosage is what the solver ran with: a problem that carries its own
     * toggles — a client's body on {@code POST /api/planning/solve} — is
     * charged with those, not with the edition's.
     */
    @Test
    void theDosageOfASolveIsTheTogglesTheProblemCarried() {
        String first = createEdition("Historique first");
        importScenario(first);

        Dosage dosage = editionContext.executeIn(first, () -> {
            PlanningEvenement probleme = planningService.buildFromReferenceData();
            probleme.setConstraintsDesactivees(new ArrayList<>(List.of(new ConstraintToggle(RULE, false))));
            solvePipeline.execute(probleme, 2L);
            return planDosage.current();
        });

        assertThat(dosage).isNotNull();
        assertThat(dosage.disabled()).contains(RULE);
    }

    /**
     * A solve write clears the previous solve's dosage before the new one is
     * stamped: a stamp that fails leaves the plan's dosage unknown, never the
     * one of a plan it replaced. A write outside a solve leaves it alone.
     */
    @Test
    void aSolveWriteClearsThePreviousDosage() {
        String first = createEdition("Historique first");
        importScenario(first);
        Dosage stamped = new Dosage(Map.of(RULE, 5), Map.of(), List.of(), List.of());

        editionContext.executeIn(first, () -> {
            PlanningEvenement plan = planningService.buildFromReferenceData();
            persistence.persistAfterSolve(plan, null);
            planDosage.record(stamped);
            persistence.persist(plan);
            assertThat(planDosage.current()).isEqualTo(stamped);

            persistence.persistAfterSolve(plan, null);
            assertThat(planDosage.current()).isNull();
        });
    }

    private List<WeightChange> changesOf(String edition) {
        return editionContext.executeIn(
                edition, () -> weightHistory.forConstraint(RULE).changes());
    }

    private static void setWeight(String edition, String poids) {
        given().header(HEADER, edition)
                .contentType("application/json")
                .body("{\"poids\":" + poids + "}")
                .when()
                .put("/api/constraints/" + RULE + "/poids")
                .then()
                .statusCode(200);
    }

    private static void importScenario(String edition) {
        given().header(HEADER, edition)
                .when()
                .post("/api/reference-data/import-scenario?name=scenario.yml")
                .then()
                .statusCode(200);
    }

    private String createEdition(String nom) {
        String id = given().contentType("application/json")
                .body("{\"nom\":\"" + nom + "\"}")
                .when()
                .post("/api/editions")
                .then()
                .statusCode(200)
                .extract()
                .path("id");
        created.add(id);
        return id;
    }
}
