package dev.sylvain.planning.scenario;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Guards {@code docs/schema/scenario-schema.json} against drifting from the
 * DTOs it is generated from.
 *
 * <p>The schema is regenerated by an <b>opt-in</b> Maven profile
 * ({@code ./mvnw process-classes -Pgenerate-schema}) that neither the default
 * build nor CI runs, so nothing forced a developer adding a field to a scenario
 * DTO to refresh it. That is exactly what happened with two fields of the
 * (since removed) découpage section: both were added to their DTO and
 * correctly parsed by the import, but stayed absent from the published
 * schema — an editor validating a scenario against it flagged two perfectly
 * valid keys as unknown, silently, for a whole release cycle.
 *
 * <p>This test closes that hole: it fails the ordinary build as soon as the
 * committed file and the generator disagree.
 */
class ScenarioSchemaGeneratorTest {

    /**
     * Compares the <b>serialised</b> forms, byte for byte, exactly as
     * {@code ScenarioSchemaGenerator.main} writes them — not the two
     * {@link JsonNode} trees. Jackson's {@code JsonNode.equals} is sensitive to
     * the concrete numeric node type, and a round-trip through text turns the
     * generator's {@code BigDecimal} bounds into {@code IntNode}: comparing
     * trees reports every {@code minimum: 0} as different from itself. The file
     * on disk is text, so text is also the right thing to assert — this catches
     * formatting drift as well as content drift.
     */
    @Test
    void leSchemaCommitteEstIdentiqueAuSchemaGenere() throws IOException {
        assertThat(ScenarioSchemaGenerator.SCHEMA_PATH)
                .as("le schéma publié doit exister")
                .exists();

        String attendu = new ObjectMapper()
                        .writerWithDefaultPrettyPrinter()
                        .writeValueAsString(ScenarioSchemaGenerator.generate())
                + System.lineSeparator();

        assertThat(Files.readString(ScenarioSchemaGenerator.SCHEMA_PATH))
                .as(
                        "%s est désynchronisé des DTO de scénario. "
                                + "Régénérez-le avec ./mvnw process-classes -Pgenerate-schema puis committez-le.",
                        ScenarioSchemaGenerator.SCHEMA_PATH)
                .isEqualTo(attendu);
    }

    /**
     * Spells out a few legal fields, so a failure names them rather than
     * dumping a whole-document diff. Redundant with the equality check above by
     * design — it is the readable half.
     *
     * <p>{@code dureeVacationMaxMinutes} is here on purpose: it is the one
     * setting the découpage left behind, and the schema is where an author
     * discovers it moved.</p>
     */
    @Test
    void leSchemaExposeLesChampsLegaux() {
        JsonNode legaux = ScenarioSchemaGenerator.generate()
                .path("$defs")
                .path("ParametresLegauxDto")
                .path("properties");

        assertThat(champs(legaux)).contains("dureePauseMinutes", "dureeVacationMaxMinutes", "coupureRepasMinutes");
    }

    /** The découpage sections are gone from the DTO tree, so the schema must not name them. */
    @Test
    void leSchemaNeNommePlusLesSectionsDuDecoupage() {
        JsonNode defs = ScenarioSchemaGenerator.generate().path("$defs");

        assertThat(champs(defs)).doesNotContain("ParametresDecoupageDto", "DecoupageAutoDto");
    }

    private static List<String> champs(JsonNode properties) {
        List<String> noms = new ArrayList<>();
        properties.fieldNames().forEachRemaining(noms::add);
        return noms;
    }
}
