package dev.sylvain.planning.service.referentiel;

import dev.sylvain.planning.domain.Emplacement;
import dev.sylvain.planning.service.BusinessError;
import dev.sylvain.planning.service.ConcurrentModificationGuard;
import dev.sylvain.planning.service.JdbcEditionScope;
import dev.sylvain.planning.service.WriteStamp;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * The emplacement rows stands are pinned to — a flat referential, and the only
 * one with coordinates.
 *
 * <p>Its id is generated by the database (decision 0049, D1), so a creation
 * and an update are two statements rather than one upsert: there is no id left
 * to conflict on, and the row an insert lands on is always a new one. What can
 * still collide is the optional {@code code}, unique within the edition, and
 * the unique index is what says so — a probe before the insert would leave the
 * window between the two open.</p>
 */
@ApplicationScoped
public class EmplacementRepository {

    /** PostgreSQL's « unique_violation »: the only collision this table can still have. */
    private static final String UNIQUE_VIOLATION = "23505";

    private static final String CODE_INDEX = "emplacement_code_unique";

    @Inject
    ConcurrentModificationGuard staleWrites;

    @Inject
    DataSource dataSource;

    @Inject
    JdbcEditionScope scope;

    public List<Emplacement> listEmplacements() {
        List<Emplacement> emplacements = new ArrayList<>();
        try (Connection connection = dataSource.getConnection();
                PreparedStatement ps = scope.prepareScoped(
                        connection,
                        "SELECT id, code, nom, latitude, longitude, modifie_le FROM emplacement WHERE edition_id = ? ORDER BY id");
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                emplacements.add(read(rs));
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to list emplacements", e);
        }
        return emplacements;
    }

    public boolean emplacementExists(long id) {
        return scope.exists("emplacement", id);
    }

    /**
     * The id the {@code code} names in this edition, or {@code null} — the
     * lookup every file goes through, since a file cites a code and never a
     * number (decision 0049, D2). Case insensitive, like the unique index.
     */
    public Long idOfCode(String code) {
        if (code == null || code.isBlank()) {
            return null;
        }
        return scope.read("Failed to resolve the emplacement code " + code, connection -> idOfCode(connection, code));
    }

    /** The same lookup inside a caller's transaction, so it sees that transaction's own writes. */
    Long idOfCode(Connection connection, String code) throws SQLException {
        if (code == null || code.isBlank()) {
            return null;
        }
        try (PreparedStatement ps = scope.prepareScoped(
                connection, "SELECT id FROM emplacement WHERE edition_id = ? AND UPPER(code) = UPPER(?)")) {
            ps.setString(2, code);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong("id") : null;
            }
        }
    }

    /** Inserts a new row; the generated id is set back onto {@code emplacement} and returned. */
    public Emplacement insertEmplacement(Emplacement emplacement) {
        return scope.writeAndReturn(
                "Failed to create an emplacement", connection -> insertEmplacementTx(connection, emplacement));
    }

    /** The same insert inside a caller's transaction. */
    Emplacement insertEmplacementTx(Connection connection, Emplacement emplacement) throws SQLException {
        try (PreparedStatement ps = scope.prepareScoped(connection, """
                INSERT INTO emplacement (edition_id, code, nom, latitude, longitude)
                VALUES (?, ?, ?, ?, ?)
                RETURNING id, modifie_le""")) {
            ps.setString(2, emplacement.getCode());
            ps.setString(3, emplacement.getNom());
            ps.setObject(4, emplacement.getLatitude());
            ps.setObject(5, emplacement.getLongitude());
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                emplacement.setId(rs.getLong("id"));
                emplacement.setModifieLe(
                        rs.getObject("modifie_le", OffsetDateTime.class).toInstant());
            }
        } catch (SQLException e) {
            throw refuseIfDuplicateCode(e, emplacement.getCode());
        }
        return emplacement;
    }

    /** Updates an existing row, refusing a write based on an out-of-date read (issue #362). */
    public void updateEmplacement(Emplacement emplacement) {
        scope.write(
                "Failed to save emplacement " + emplacement.getId(),
                connection -> updateEmplacementTx(connection, emplacement));
    }

    /** The same write inside a caller's transaction. */
    void updateEmplacementTx(Connection connection, Emplacement emplacement) throws SQLException {
        // Not prepareScoped: an UPDATE's first placeholder belongs to its SET
        // clause, so the edition predicate can't be the statement's first one.
        try (PreparedStatement ps = connection.prepareStatement("""
                UPDATE emplacement
                SET code = ?, nom = ?, latitude = ?, longitude = ?, modifie_le = now()
                WHERE edition_id = ? AND id = ?
                AND (CAST(? AS timestamptz) IS NULL
                     OR date_trunc('milliseconds', emplacement.modifie_le)
                        = date_trunc('milliseconds', CAST(? AS timestamptz)))
                RETURNING modifie_le""")) {
            ps.setString(1, emplacement.getCode());
            ps.setString(2, emplacement.getNom());
            ps.setObject(3, emplacement.getLatitude());
            ps.setObject(4, emplacement.getLongitude());
            ps.setString(5, scope.editionId());
            ps.setLong(6, emplacement.getId());
            WriteStamp.bindPrecondition(ps, 7, true, emplacement.getModifieLe());
            Instant ecrit = WriteStamp.writtenOrRefused(ps);
            if (ecrit == null) {
                staleWrites.refuseStale("emplacement", emplacement.getId());
            }
            emplacement.setModifieLe(ecrit);
        } catch (SQLException e) {
            throw refuseIfDuplicateCode(e, emplacement.getCode());
        }
    }

    public void deleteEmplacement(long id) {
        scope.delete("DELETE FROM emplacement WHERE edition_id = ? AND id = ?", id);
    }

    /**
     * The unique index said the code is taken. Detected by the write itself,
     * which is the only way to be sure: a probe before it leaves a window in
     * which a concurrent creation lands.
     */
    private SQLException refuseIfDuplicateCode(SQLException e, String code) {
        if (UNIQUE_VIOLATION.equals(e.getSQLState())
                && e.getMessage() != null
                && e.getMessage().contains(CODE_INDEX)) {
            throw new BusinessError.Conflict("Le code « " + code + " » est déjà pris par un autre emplacement de "
                    + "cette édition. Choisissez-en un autre, ou laissez-le vide.");
        }
        return e;
    }

    private Emplacement read(ResultSet rs) throws SQLException {
        Emplacement emplacement =
                new Emplacement(rs.getLong("id"), rs.getString("nom"), (Double) rs.getObject("latitude"), (Double)
                        rs.getObject("longitude"));
        emplacement.setCode(rs.getString("code"));
        emplacement.setModifieLe(
                rs.getObject("modifie_le", OffsetDateTime.class).toInstant());
        return emplacement;
    }
}
