package dev.sylvain.planning.service.referentiel;

import dev.sylvain.planning.domain.Emplacement;
import dev.sylvain.planning.service.BusinessError;
import dev.sylvain.planning.service.ReferenceDataChangeTracker;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/** CRUD of the emplacement referential — the physical places stands sit in. */
@ApplicationScoped
public class EmplacementService {

    /** As long as the column, and long enough for what a file writes in that cell. */
    private static final int CODE_MAX = 64;

    @Inject
    EmplacementRepository repository;

    @Inject
    ReferenceDataChangeTracker changeTracker;

    public List<Emplacement> list() {
        return repository.listEmplacements();
    }

    /**
     * Creates one. The id is not read from the caller — it is generated by the
     * database (decision 0049, D1) — so a body carrying one is ignored rather
     * than refused: an old client sending back what it last read must not
     * silently overwrite that row.
     */
    public Emplacement create(Emplacement emplacement) {
        emplacement.setId(null);
        validate(emplacement);
        repository.insertEmplacement(emplacement);
        changeTracker.markModified();
        return emplacement;
    }

    /**
     * {@link #create(Emplacement)} inside a caller's transaction: written with
     * the rest, or not at all. The caller marks the referential modified once
     * its transaction is committed (see {@code TypologieService}).
     */
    Emplacement create(Connection connection, Emplacement emplacement) throws SQLException {
        emplacement.setId(null);
        validate(emplacement);
        return repository.insertEmplacementTx(connection, emplacement);
    }

    public Emplacement update(long id, Emplacement emplacement) {
        if (!repository.emplacementExists(id)) {
            throw new BusinessError.NotFound("Emplacement inconnu : " + id);
        }
        emplacement.setId(id);
        validate(emplacement);
        repository.updateEmplacement(emplacement);
        changeTracker.markModified();
        return emplacement;
    }

    public void delete(long id) {
        repository.deleteEmplacement(id);
        changeTracker.markModified();
    }

    /**
     * The id a file names, since a file cites a code and never a number
     * (decision 0049, D2). Refuses a code naming nothing rather than answering
     * {@code null}: a stand whose emplacement silently vanished is the failure
     * this lookup exists to prevent.
     */
    public long idOfCode(String code) {
        Long id = repository.idOfCode(code);
        if (id == null) {
            throw new BusinessError.Invalid("Aucun emplacement de cette édition ne porte le code « " + code + " »");
        }
        return id;
    }

    /** The same lookup, answering {@code null} instead of refusing. */
    public Long idOfCodeOrNull(String code) {
        return repository.idOfCode(code);
    }

    private void validate(Emplacement emplacement) {
        if (emplacement.getNom() == null || emplacement.getNom().isBlank()) {
            throw new BusinessError.Invalid("Un emplacement porte un nom");
        }
        normaliseCode(emplacement);
        validateCoordinates(emplacement);
    }

    /** A blank code is no code: the unique index lets several rows share « none ». */
    private void normaliseCode(Emplacement emplacement) {
        String code = emplacement.getCode();
        if (code == null || code.isBlank()) {
            emplacement.setCode(null);
            return;
        }
        String trimmed = code.trim();
        if (trimmed.length() > CODE_MAX) {
            throw new BusinessError.Invalid("Le code d'un emplacement ne dépasse pas " + CODE_MAX + " caractères");
        }
        emplacement.setCode(trimmed);
    }

    private void validateCoordinates(Emplacement emplacement) {
        Double latitude = emplacement.getLatitude();
        Double longitude = emplacement.getLongitude();
        if (latitude != null && (latitude < -90 || latitude > 90)) {
            throw new BusinessError.Invalid("latitude must be between -90 and 90");
        }
        if (longitude != null && (longitude < -180 || longitude > 180)) {
            throw new BusinessError.Invalid("longitude must be between -180 and 180");
        }
    }
}
