package dev.sylvain.planning.service.referentiel;

import dev.sylvain.planning.domain.Creneau;
import dev.sylvain.planning.domain.Emplacement;
import dev.sylvain.planning.domain.JourneeType;
import dev.sylvain.planning.domain.Stand;
import dev.sylvain.planning.domain.VacationType;
import dev.sylvain.planning.service.BusinessError;
import dev.sylvain.planning.service.IdGenerator;
import dev.sylvain.planning.service.ReferenceDataChangeTracker;
import dev.sylvain.planning.service.referentiel.JourneesTypesMaterialisation.Affectation;
import dev.sylvain.planning.service.referentiel.ReferentielCsvImportReport.ActionImport;
import dev.sylvain.planning.service.referentiel.ReferentielCsvImportReport.ImportTarget;
import dev.sylvain.planning.service.referentiel.ReferentielCsvImportReport.LigneImportee;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.function.Function;
import java.util.function.ToIntFunction;

/**
 * The referentials an edition is filled from, read from a CSV: typologies,
 * emplacements, stands, the timeslot grid and the day templates, so an edition
 * starts from the spreadsheet the organiser already has rather than from sixty
 * dialogs.
 *
 * <p><b>A column the file does not carry leaves the field alone</b>, and so
 * does an empty cell — the doctrine of the compétences grid
 * ({@code docs/decisions/0030}) applied to a fiche: a three-column file
 * renaming stands must not erase their opening hours, their emplacement or
 * their flags. Only what is written is written.</p>
 *
 * <p>Previewing and writing run the same analysis; the write re-reads the file
 * rather than trusting what the browser was shown, exactly as
 * {@link AnimateurCsvImportService} does.</p>
 *
 * <p>The last two targets are not fiches and are keyed differently. A
 * <b>timeslot</b> has no identifier of its own — its id is generated by the
 * database and reassigned by a scenario import — so the file is matched on
 * {@code (date, heure de début, heure de fin)}, the only thing about it that
 * travels. A <b>day template</b> is matched on its name, and its dates are
 * merged into the calendar rather than replacing it; materialising that
 * calendar into timeslots stays the explicit « Appliquer » of the Journées
 * types screen, with its own preview (ADR 0032): a template is a generator,
 * never the truth, and an import that silently rewrote the grid would be the
 * one gesture that doctrine forbids.</p>
 */
@ApplicationScoped
public class ReferentielCsvImportService {

    /** A stand the file does not size holds one person: enough to produce a seat, small enough to be obviously provisional. */
    static final int EFFECTIF_PAR_DEFAUT = 1;

    private static final int MAX_CHARACTERS = 1_000_000;

    private static final int MAX_ROWS = 5_000;

    private static final String ZIP_SIGNATURE = "PK";

    /** How a cell lists several values, as the animateur import already reads them — never a slash, a date uses it. */
    private static final String SEPARATEUR_MULTI = "[|;,\\n]";

    private static final String DEJA_PLUS_HAUT = " » apparaît déjà plus haut dans le fichier.";

    private final TypologieService typologies;

    private final EmplacementService emplacements;

    private final StandService stands;

    private final CreneauService creneaux;

    private final JourneeTypeService journeesTypes;

    private final ReferenceDataChangeTracker changeTracker;

    @Inject
    public ReferentielCsvImportService(
            TypologieService typologies,
            EmplacementService emplacements,
            StandService stands,
            CreneauService creneaux,
            JourneeTypeService journeesTypes,
            ReferenceDataChangeTracker changeTracker) {
        this.typologies = typologies;
        this.emplacements = emplacements;
        this.stands = stands;
        this.creneaux = creneaux;
        this.journeesTypes = journeesTypes;
        this.changeTracker = changeTracker;
    }

    /* ------------------------------- Entry points ------------------------------- */

    public ReferentielCsvImportReport preview(ImportTarget cible, ReferentielCsvImportRequest request) {
        return analyse(cible, request).report(false);
    }

    /** Writes what the preview announced, row by row, after reading the file again. */
    public ReferentielCsvImportReport apply(ImportTarget cible, ReferentielCsvImportRequest request) {
        Analyse analyse = analyse(cible, request);
        for (String code : analyse.typologiesACreer()) {
            typologies.importer(new TypologieItem(null, code, code, false, null, null, null));
        }
        for (Ecriture ecriture : analyse.ecritures()) {
            ecriture.ecrire(this);
        }
        if (analyse.marqueModification()
                && (!analyse.ecritures().isEmpty()
                        || !analyse.typologiesACreer().isEmpty())) {
            changeTracker.markModified();
        }
        return analyse.report(true);
    }

    /** The file the screen offers to download, so the shape is shown rather than described. */
    public String exemple(ImportTarget cible) {
        return switch (cible) {
            case TYPOLOGIES -> """
                    code;libelle;ninja
                    AMBIANCE;Jeux d'ambiance;
                    STRATEGIE;Jeux de stratégie;
                    POLYVALENT;Polyvalent;oui
                    """;
            case EMPLACEMENTS -> """
                    code;nom;latitude;longitude
                    PAVILLON;Pavillon central;46.6503;-0.2461
                    CHAPITEAU;Chapiteau nord;46.6511;-0.2447
                    EXTERIEUR;Esplanade;;
                    """;
            case STANDS -> """
                    code;nom;typologies;effectifMin;effectifMax
                    FAMILLES;Stand des familles;AMBIANCE;2;3
                    STRATEGIE;Stand stratégie;STRATEGIE|AMBIANCE;1;2
                    DECOUVERTE;Stand découverte;AMBIANCE;;
                    """;
            case CRENEAUX -> """
                    date;heureDebut;heureFin;couverturePause
                    2026-07-10;09:00;12:00;
                    2026-07-10;12:00;13:00;oui
                    2026-07-10;13:00;20:00;
                    2026-07-11;20:00;00:00;
                    """;
            case JOURNEES_TYPES -> """
                    nom;vacations;dates
                    Jour normal;"09:00-12:00, 12:00-13:00 R, 13:00-20:00";2026-07-10|2026-07-11
                    Nocturne;"14:00-20:00, 20:00-00:00";2026-07-12
                    Montage;"08:00-12:00";
                    """;
        };
    }

    public static String exampleFileName(ImportTarget cible) {
        return switch (cible) {
            case TYPOLOGIES -> "exemple-typologies.csv";
            case EMPLACEMENTS -> "exemple-emplacements.csv";
            case STANDS -> "exemple-stands.csv";
            case CRENEAUX -> "exemple-creneaux.csv";
            case JOURNEES_TYPES -> "exemple-journees-types.csv";
        };
    }

    /* ------------------------------- Analysis ------------------------------- */

    private Analyse analyse(ImportTarget cible, ReferentielCsvImportRequest request) {
        refuseSpreadsheet(request.fileName(), request.content());
        String contenu = request.content() == null ? "" : request.content();
        if (contenu.isBlank()) {
            throw new BusinessError.Invalid("Le fichier est vide.");
        }
        if (contenu.length() > MAX_CHARACTERS) {
            throw new BusinessError.Invalid(
                    "Fichier trop volumineux : " + groupe(MAX_CHARACTERS) + " caractères au maximum.");
        }
        CsvParser.Table table = CsvParser.parse(contenu);
        if (table.rows().size() > MAX_ROWS) {
            throw new BusinessError.Invalid("Fichier trop long : " + groupe(MAX_ROWS) + " lignes au maximum.");
        }
        Colonnes colonnes = Colonnes.of(cible, table.columns());
        return switch (cible) {
            case TYPOLOGIES -> analyseTypologies(table, colonnes);
            case EMPLACEMENTS -> analyseEmplacements(table, colonnes);
            case STANDS -> analyseStands(table, colonnes);
            case CRENEAUX -> analyseCreneaux(table, colonnes);
            case JOURNEES_TYPES -> analyseJourneesTypes(table, colonnes);
        };
    }

    /**
     * Which row of the referential a line designates, and under which code
     * (ADR 0050). The {@code code} column is the key. The {@code id} column,
     * when the file carries one, names a row by the id the application gave
     * it — the shape of an export — and is ignored when this edition has no
     * such row (a file exported from another edition): numbers are per
     * edition, so the same id designates something else there. In a file
     * written before ids were generated the {@code id} column holds what is
     * now the code, and is read as one.
     *
     * @param id     the existing row designated, {@code null} for a creation
     * @param code   the code to write, {@code null} for none
     * @param cle    what the report shows for the line
     * @param refus  why the line designates nothing, {@code null} when it does
     * @param note   what the report should add about how the line was matched
     */
    private record Cle(String id, String code, String cle, String refus, String note) {

        static Cle of(
                CsvParser.Row row,
                Colonnes colonnes,
                IdGenerator.Kind kind,
                Map<String, String> codesParId,
                Map<String, String> idsParCode) {
            String idLu = colonnes.valeur(row, "id");
            String codeLu = colonnes.valeur(row, "code");
            if (!idLu.isBlank() && codesParId.containsKey(idLu)) {
                String code = codeLu.isBlank() ? codesParId.get(idLu) : codeLu;
                return new Cle(idLu, code, idLu, null, null);
            }
            String code = codeLu.isBlank() && !kind.hasGeneratedShape(idLu) ? idLu : codeLu;
            String note = !idLu.isBlank() && !idLu.equals(code)
                    ? "L'identifiant « " + idLu + " » n'existe pas dans cette édition : il est ignoré."
                    : null;
            if (code.isBlank()) {
                if (idLu.isBlank()) {
                    return new Cle(
                            null, null, null, "La colonne « code » est vide : c'est elle qui désigne la ligne.", null);
                }
                return new Cle(null, null, idLu, null, note);
            }
            return new Cle(idsParCode.get(code), code, code, null, note);
        }

        /** The same row twice in one file is a mistake whichever way it is named. */
        String cible() {
            if (id != null) {
                return "id:" + id;
            }
            return code != null ? "code:" + code : "ligne:" + System.identityHashCode(this);
        }
    }

    /** A coded referential as the analysis matches lines on: its rows by id, their codes, and back. */
    private record Coded<T>(Map<String, T> parId, Map<String, String> codesParId, Map<String, String> idsParCode) {

        static <T> Coded<T> of(List<T> rows, Function<T, String> id, Function<T, String> code) {
            Map<String, T> parId = new LinkedHashMap<>();
            Map<String, String> codesParId = new LinkedHashMap<>();
            Map<String, String> idsParCode = new LinkedHashMap<>();
            for (T row : rows) {
                parId.put(id.apply(row), row);
                codesParId.put(id.apply(row), code.apply(row));
                if (code.apply(row) != null) {
                    idsParCode.put(code.apply(row), id.apply(row));
                }
            }
            return new Coded<>(parId, codesParId, idsParCode);
        }

        Cle key(CsvParser.Row row, Colonnes colonnes, IdGenerator.Kind kind) {
            return Cle.of(row, colonnes, kind, codesParId, idsParCode);
        }
    }

    private Analyse analyseTypologies(CsvParser.Table table, Colonnes colonnes) {
        Coded<TypologieItem> existantes = Coded.of(typologies.list(), TypologieItem::id, TypologieItem::code);
        List<LigneImportee> lignes = new ArrayList<>();
        List<Ecriture> ecritures = new ArrayList<>();
        Set<String> vus = new LinkedHashSet<>();
        for (CsvParser.Row row : table.rows()) {
            lignes.add(analyseTypologie(row, colonnes, existantes, vus, ecritures));
        }
        return new Analyse(ImportTarget.TYPOLOGIES, table, lignes, ecritures, List.of());
    }

    private static LigneImportee analyseTypologie(
            CsvParser.Row row,
            Colonnes colonnes,
            Coded<TypologieItem> existantes,
            Set<String> vus,
            List<Ecriture> ecritures) {
        Cle cle = existantes.key(row, colonnes, IdGenerator.Kind.TYPOLOGIE);
        String libelle = colonnes.valeur(row, "libelle");
        List<String> raisons = new ArrayList<>();
        if (libelle.isBlank()) {
            raisons.add("La colonne « libelle » est vide : c'est le nom lu à l'écran.");
        }
        checkKey(cle, vus, raisons);
        if (raisons.isEmpty()) {
            checkCode(cle, IdGenerator.Kind.TYPOLOGIE, raisons);
        }
        if (!raisons.isEmpty()) {
            return refusedRow(row, cle.cle(), libelle, raisons);
        }
        boolean ninja = readFlag(colonnes.valeur(row, "ninja"));
        List<String> details = new ArrayList<>();
        if (cle.note() != null) {
            details.add(cle.note());
        }
        if (ninja) {
            details.add("Marquée polyvalente : elle retire le drapeau à la typologie qui le portait.");
        }
        // The file carries code, libelle and ninja — no cap and no
        // description column — so both are kept rather than erased: « une
        // colonne retirée du fichier n'efface rien » (docs/import-export.md).
        TypologieItem existante = cle.id() == null ? null : existantes.parId().get(cle.id());
        TypologieItem ecrite = new TypologieItem(
                cle.id(),
                cle.code(),
                libelle,
                ninja,
                existante == null ? null : existante.maxCreneauxParAnimateur(),
                existante == null ? null : existante.description(),
                null);
        ecritures.add(service -> service.typologies.importer(ecrite));
        return new LigneImportee(
                row.line(),
                cle.cle(),
                libelle,
                existante != null ? ActionImport.MIS_A_JOUR : ActionImport.CREE,
                List.of(),
                details);
    }

    private Analyse analyseEmplacements(CsvParser.Table table, Colonnes colonnes) {
        Coded<Emplacement> existants = Coded.of(emplacements.list(), Emplacement::getId, Emplacement::getCode);
        List<LigneImportee> lignes = new ArrayList<>();
        List<Ecriture> ecritures = new ArrayList<>();
        Set<String> vus = new LinkedHashSet<>();
        for (CsvParser.Row row : table.rows()) {
            lignes.add(analyseEmplacement(row, colonnes, existants, vus, ecritures));
        }
        return new Analyse(ImportTarget.EMPLACEMENTS, table, lignes, ecritures, List.of());
    }

    private static LigneImportee analyseEmplacement(
            CsvParser.Row row,
            Colonnes colonnes,
            Coded<Emplacement> existants,
            Set<String> vus,
            List<Ecriture> ecritures) {
        Cle cle = existants.key(row, colonnes, IdGenerator.Kind.EMPLACEMENT);
        String nom = colonnes.valeur(row, "nom");
        Emplacement existant = cle.id() == null ? null : existants.parId().get(cle.id());
        List<String> raisons = new ArrayList<>();
        checkKeyAndName(cle, nom, existant != null, "l'emplacement", vus, raisons);
        Double latitude = null;
        Double longitude = null;
        try {
            latitude = readCoordinate(colonnes.valeur(row, "latitude"), "latitude");
            longitude = readCoordinate(colonnes.valeur(row, "longitude"), "longitude");
        } catch (BusinessError.Invalid e) {
            raisons.add(e.getMessage());
        }
        checkCode(cle, IdGenerator.Kind.EMPLACEMENT, raisons);
        if (!raisons.isEmpty()) {
            return refusedRow(row, cle.cle(), nom, raisons);
        }
        Emplacement ecrit = new Emplacement();
        ecrit.setId(cle.id());
        ecrit.setCode(cle.code());
        ecrit.setNom(nom.isBlank() ? existant.getNom() : nom);
        // An absent column, or an empty cell, never takes away what is there.
        ecrit.setLatitude(readOrKept(latitude, existant, Emplacement::getLatitude));
        ecrit.setLongitude(readOrKept(longitude, existant, Emplacement::getLongitude));
        List<String> details = new ArrayList<>();
        if (cle.note() != null) {
            details.add(cle.note());
        }
        if (ecrit.getLatitude() == null || ecrit.getLongitude() == null) {
            details.add("Sans coordonnées : l'emplacement ne pèsera pas sur les distances entre stands.");
        }
        String id = cle.id();
        ecritures.add(
                existant == null
                        ? service -> service.emplacements.create(ecrit)
                        : service -> service.emplacements.update(id, ecrit));
        return new LigneImportee(
                row.line(),
                cle.cle(),
                ecrit.getNom(),
                existant == null ? ActionImport.CREE : ActionImport.MIS_A_JOUR,
                List.of(),
                details);
    }

    /** The coordinate the file gives, else the one the emplacement already has, else none. */
    private static Double readOrKept(Double lue, Emplacement existant, Function<Emplacement, Double> champ) {
        if (lue != null) {
            return lue;
        }
        return existant == null ? null : champ.apply(existant);
    }

    private Analyse analyseStands(CsvParser.Table table, Colonnes colonnes) {
        Coded<Stand> existants = Coded.of(stands.list(), Stand::getId, Stand::getCode);
        Map<String, String> typologiesParCle = new LinkedHashMap<>();
        typologies.list().forEach(typologie -> {
            if (typologie.code() != null) {
                typologiesParCle.putIfAbsent(typologie.code(), typologie.id());
            }
            typologiesParCle.put(typologie.id(), typologie.id());
        });
        Set<String> aCreer = new TreeSet<>();
        List<LigneImportee> lignes = new ArrayList<>();
        List<Ecriture> ecritures = new ArrayList<>();
        Set<String> vus = new LinkedHashSet<>();
        for (CsvParser.Row row : table.rows()) {
            lignes.add(analyseStand(row, colonnes, existants, typologiesParCle, aCreer, vus, ecritures));
        }
        return new Analyse(ImportTarget.STANDS, table, lignes, ecritures, List.copyOf(aCreer));
    }

    private static LigneImportee analyseStand(
            CsvParser.Row row,
            Colonnes colonnes,
            Coded<Stand> existants,
            Map<String, String> typologiesParCle,
            Set<String> aCreer,
            Set<String> vus,
            List<Ecriture> ecritures) {
        Cle cle = existants.key(row, colonnes, IdGenerator.Kind.STAND);
        String nom = colonnes.valeur(row, "nom");
        Stand existant = cle.id() == null ? null : existants.parId().get(cle.id());
        List<String> raisons = new ArrayList<>();
        List<String> details = new ArrayList<>();
        if (cle.note() != null) {
            details.add(cle.note());
        }
        checkKeyAndName(cle, nom, existant != null, "le stand", vus, raisons);
        List<String> typologiesLues = valeursMultiples(colonnes.valeur(row, "typologies"));
        Set<String> typologiesStand = new LinkedHashSet<>(
                typologiesLues.isEmpty() && existant != null ? existant.getTypologiesProposees() : typologiesLues);
        if (typologiesStand.isEmpty()) {
            raisons.add("Aucune typologie : un stand est toujours rattaché à au moins une typologie de jeu.");
        }
        for (String typologie : typologiesStand) {
            if (!typologiesParCle.containsKey(typologie) && IdGenerator.Kind.TYPOLOGIE.hasGeneratedShape(typologie)) {
                raisons.add("La typologie « " + typologie + " » n'existe pas dans cette édition.");
            }
        }
        Integer effectifMin = null;
        Integer effectifMax = null;
        try {
            effectifMin = readHeadcount(colonnes.valeur(row, "effectifmin"), "effectifMin");
            effectifMax = readHeadcount(colonnes.valeur(row, "effectifmax"), "effectifMax");
        } catch (BusinessError.Invalid e) {
            raisons.add(e.getMessage());
        }
        checkCode(cle, IdGenerator.Kind.STAND, raisons);
        if (!raisons.isEmpty()) {
            return refusedRow(row, cle.cle(), nom, raisons);
        }
        int min = headcountOrKept(effectifMin, existant, Stand::getEffectifMin);
        int max = headcountOrKept(effectifMax, existant, Stand::getEffectifMax);
        if (max < min) {
            return new LigneImportee(
                    row.line(),
                    cle.cle(),
                    blankAsNull(nom),
                    ActionImport.REFUSE,
                    List.of("effectifMax (" + max + ") est inférieur à effectifMin (" + min + ")."),
                    List.of());
        }
        // Only now: a typologie is created on the strength of the stand that
        // names it, so a row the checks above have refused must not leave one
        // behind — nothing would reference it.
        announceNewTypologies(typologiesStand, typologiesParCle.keySet(), aCreer, details);
        if (existant == null && effectifMin == null && effectifMax == null) {
            details.add(
                    "Effectif non précisé : le stand tient à une personne, à ajuster sur la grille des ouvertures.");
        }
        Stand ecrit = existant == null ? new Stand() : copie(existant);
        ecrit.setId(cle.id());
        ecrit.setCode(cle.code());
        ecrit.setNom(nom.isBlank() ? existant.getNom() : nom);
        ecrit.setEffectifMin(min);
        ecrit.setEffectifMax(max);
        String id = cle.id();
        // The typologies are named by code or id in the file; the ones this
        // import creates only have an id once written, so the names are
        // resolved when the line is written, after them.
        ecritures.add(service -> {
            ecrit.setTypologiesProposees(service.typologyIds(typologiesStand));
            if (id == null) {
                service.stands.create(ecrit);
            } else {
                service.stands.update(id, ecrit);
            }
        });
        return new LigneImportee(
                row.line(),
                cle.cle(),
                ecrit.getNom(),
                existant == null ? ActionImport.CREE : ActionImport.MIS_A_JOUR,
                List.of(),
                details);
    }

    /** The headcount the file gives, else the stand's own, else the provisional default of a new stand. */
    private static int headcountOrKept(Integer lu, Stand existant, ToIntFunction<Stand> champ) {
        if (lu != null) {
            return lu;
        }
        return existant != null ? champ.applyAsInt(existant) : EFFECTIF_PAR_DEFAUT;
    }

    private static void announceNewTypologies(
            Set<String> typologiesStand, Set<String> typologiesConnues, Set<String> aCreer, List<String> details) {
        for (String typologie : typologiesStand) {
            if (!typologiesConnues.contains(typologie) && aCreer.add(typologie)) {
                details.add("La typologie « " + typologie + " » sera créée, avec ce code pour libellé.");
            }
        }
    }

    /** The typologies a stand line names, by id or by code, as ids — read when the line is written. */
    private Set<String> typologyIds(Set<String> noms) {
        Map<String, String> parCle = new LinkedHashMap<>();
        typologies.list().forEach(typologie -> {
            if (typologie.code() != null) {
                parCle.putIfAbsent(typologie.code(), typologie.id());
            }
            parCle.put(typologie.id(), typologie.id());
        });
        Set<String> ids = new LinkedHashSet<>();
        noms.forEach(nom -> ids.add(parCle.getOrDefault(nom, nom)));
        return ids;
    }

    /**
     * The timeslot grid, matched on {@code (date, heure de début, heure de
     * fin)}: a timeslot carries no identifier a file could name, and the one
     * the database generates is reassigned by the next scenario import.
     *
     * <p>A row already in the grid writes only its {@code couverturePause}
     * flag over it — everything else in that triple <b>is</b> the key — and a
     * timeslot the file leaves out is left where it is: a file covering one
     * weekend must not empty the rest of the edition.</p>
     */
    private Analyse analyseCreneaux(CsvParser.Table table, Colonnes colonnes) {
        Map<String, Creneau> existants = new LinkedHashMap<>();
        for (Creneau creneau : creneaux.list()) {
            existants.putIfAbsent(
                    creneauKey(creneau.getDate(), creneau.getHeureDebut(), creneau.getHeureFin()), creneau);
        }
        List<LigneImportee> lignes = new ArrayList<>();
        List<Creneau> aCreer = new ArrayList<>();
        List<Creneau> aMettreAJour = new ArrayList<>();
        Set<String> vus = new LinkedHashSet<>();
        for (CsvParser.Row row : table.rows()) {
            lignes.add(analyseCreneau(row, colonnes, existants, vus, aCreer, aMettreAJour));
        }
        // One write for the whole file, not one per row: the grid marker the
        // toolbar reads would otherwise announce four hundred separate edits.
        List<Ecriture> ecritures = aCreer.isEmpty() && aMettreAJour.isEmpty()
                ? List.of()
                : List.of(service -> service.creneaux.importer(aCreer, aMettreAJour));
        return new Analyse(ImportTarget.CRENEAUX, table, lignes, ecritures, List.of());
    }

    private static LigneImportee analyseCreneau(
            CsvParser.Row row,
            Colonnes colonnes,
            Map<String, Creneau> existants,
            Set<String> vus,
            List<Creneau> aCreer,
            List<Creneau> aMettreAJour) {
        String dateLue = colonnes.valeur(row, "date");
        String debutLu = colonnes.valeur(row, "heuredebut");
        String finLue = colonnes.valeur(row, "heurefin");
        List<String> raisons = new ArrayList<>();
        LocalDate date = readEventDate(dateLue, raisons);
        LocalTime debut = readTime(debutLu, "heureDebut", raisons);
        LocalTime fin = readTime(finLue, "heureFin", raisons);
        if (date != null && debut != null && debut.equals(fin)) {
            raisons.add("Début et fin identiques (« " + debutLu.trim() + " ») : le créneau n'a pas de durée.");
        }
        String cle = date == null || debut == null || fin == null ? null : creneauKey(date, debut, fin);
        if (cle != null && vus.contains(cle)) {
            raisons.add("Ce créneau apparaît déjà plus haut dans le fichier.");
        }
        if (!raisons.isEmpty()) {
            return new LigneImportee(
                    row.line(),
                    blankAsNull(dateLue),
                    libelleHoraire(debutLu, finLue),
                    ActionImport.REFUSE,
                    raisons,
                    List.of());
        }
        // Claimed only now: a row refused for another reason must not make
        // the next one look like its duplicate.
        vus.add(cle);
        boolean couverturePause = readFlag(colonnes.valeur(row, "couverturepause"));
        List<String> details = new ArrayList<>();
        if (couverturePause) {
            details.add("Relais repas : le stand n'ouvre que la moitié de son effectif, arrondie au supérieur.");
        }
        if (!fin.isAfter(debut)) {
            details.add("Se termine le lendemain : la vacation passe minuit.");
        }
        Creneau existant = existants.get(cle);
        Creneau ecrit = new Creneau(existant == null ? null : existant.getId(), 0, date, debut, fin);
        ecrit.setCouverturePause(couverturePause);
        if (existant == null) {
            aCreer.add(ecrit);
        } else {
            aMettreAJour.add(ecrit);
        }
        return new LigneImportee(
                row.line(),
                date.toString(),
                libelleHoraire(debutLu, finLue),
                existant == null ? ActionImport.CREE : ActionImport.MIS_A_JOUR,
                List.of(),
                details);
    }

    /**
     * Day templates and the dates they govern — one row per template, its
     * shifts on the compact line {@link VacationsLigne} reads and its dates in
     * a multi-value cell.
     *
     * <p>The calendar is <b>merged</b>, never replaced: a date the file names
     * changes template, a date it does not is left as it was. And nothing is
     * materialised — the grid moves only when somebody presses « Appliquer »
     * on the Journées types screen, which previews what it would change first
     * (ADR 0032).</p>
     */
    private Analyse analyseJourneesTypes(CsvParser.Table table, Colonnes colonnes) {
        DayTemplateReader lecture = new DayTemplateReader();
        journeesTypes
                .list()
                .forEach(journeeType -> lecture.existants.putIfAbsent(nomNormalise(journeeType.getNom()), journeeType));
        Map<Long, String> nomsParId = new LinkedHashMap<>();
        journeesTypes.list().forEach(journeeType -> nomsParId.put(journeeType.getId(), journeeType.getNom()));
        journeesTypes
                .calendrier()
                .forEach(affectation ->
                        lecture.calendrierActuel.put(affectation.date(), nomsParId.get(affectation.journeeTypeId())));

        List<LigneImportee> lignes = new ArrayList<>();
        for (CsvParser.Row row : table.rows()) {
            lignes.add(lecture.read(row, colonnes));
        }

        List<Ecriture> ecritures = new ArrayList<>();
        for (JourneeType journeeType : lecture.valides) {
            ecritures.add(service -> {
                if (journeeType.getId() == null) {
                    service.journeesTypes.create(journeeType);
                } else {
                    service.journeesTypes.update(journeeType.getId(), journeeType);
                }
            });
        }
        if (!lecture.valides.isEmpty()) {
            // Last, and only once: a template created above has no id until it
            // is written, and the calendar is rewritten whole by its service.
            Map<String, List<LocalDate>> datesParNom = lecture.datesParNom;
            ecritures.add(service -> service.mergeCalendrier(datesParNom));
        }
        // Nothing the solver reads has moved — the grid is untouched until the
        // calendar is applied — so the edition is not marked as modified.
        return new Analyse(ImportTarget.JOURNEES_TYPES, table, lignes, ecritures, List.of(), false);
    }

    /** The day-template rows read so far: what the next row is checked against. */
    private static final class DayTemplateReader {

        private final Map<String, JourneeType> existants = new LinkedHashMap<>();
        private final Map<LocalDate, String> calendrierActuel = new TreeMap<>();
        private final List<JourneeType> valides = new ArrayList<>();
        private final Map<String, List<LocalDate>> datesParNom = new LinkedHashMap<>();
        private final Map<LocalDate, String> revendiquees = new LinkedHashMap<>();
        private final Set<String> vus = new LinkedHashSet<>();

        LigneImportee read(CsvParser.Row row, Colonnes colonnes) {
            String nom = colonnes.valeur(row, "nom");
            String vacationsLues = colonnes.valeur(row, "vacations");
            List<String> raisons = new ArrayList<>();
            if (!nom.isBlank() && vus.contains(nomNormalise(nom))) {
                raisons.add("La journée type « " + nom.strip() + DEJA_PLUS_HAUT);
            }
            List<VacationType> vacations = List.of();
            try {
                vacations = VacationsLigne.parse(vacationsLues);
            } catch (BusinessError.Invalid e) {
                raisons.add(e.getMessage());
            }
            JourneeType existant = existants.get(nomNormalise(nom));
            JourneeType lue = new JourneeType(existant == null ? null : existant.getId(), nom, vacations);
            if (raisons.isEmpty()) {
                validate(lue, raisons);
            }
            List<LocalDate> dates = readDates(colonnes.valeur(row, "dates"), nom, raisons);
            if (!raisons.isEmpty()) {
                return refusedRow(row, nom, vacationsLues, raisons);
            }
            // The name and the dates are claimed only now, for the reason the
            // timeslot tab gives: a row refused for something else must not
            // make the next one collide with it.
            vus.add(nomNormalise(lue.getNom()));
            dates.forEach(date -> revendiquees.put(date, lue.getNom()));
            valides.add(lue);
            datesParNom.put(nomNormalise(lue.getNom()), dates);
            return new LigneImportee(
                    row.line(),
                    lue.getNom(),
                    VacationsLigne.format(lue.getVacations()),
                    existant == null ? ActionImport.CREE : ActionImport.MIS_A_JOUR,
                    List.of(),
                    details(lue, dates));
        }

        /**
         * The same rules the screen and the scenario section obey — a blank
         * name, a zero-length shift, two identical shifts — read against the
         * rows already accepted rather than against the database, so a file
         * naming one template twice is caught even when neither exists yet.
         */
        private void validate(JourneeType lue, List<String> raisons) {
            try {
                JourneeTypeService.validate(lue, valides);
            } catch (BusinessError.Invalid e) {
                raisons.add(e.getMessage());
            }
        }

        private List<LocalDate> readDates(String cellule, String nom, List<String> raisons) {
            List<LocalDate> dates = new ArrayList<>();
            for (String valeur : valeursMultiples(cellule)) {
                LocalDate date = readEventDate(valeur, raisons);
                if (date != null) {
                    String revendiquePar = revendiquees.get(date);
                    if (revendiquePar != null || dates.contains(date)) {
                        String titulaire = revendiquePar == null ? nom.strip() : revendiquePar;
                        raisons.add("Le " + date + " est déjà affecté à « " + titulaire + " » dans ce fichier.");
                    } else {
                        dates.add(date);
                    }
                }
            }
            return dates;
        }

        private List<String> details(JourneeType lue, List<LocalDate> dates) {
            List<String> details = new ArrayList<>();
            if (dates.isEmpty()) {
                details.add("Aucune date : la journée type existe, elle ne gouverne encore aucun jour.");
            } else {
                details.add(dates.size() + " date(s) affectée(s), du "
                        + dates.stream().min(LocalDate::compareTo).orElseThrow() + " au "
                        + dates.stream().max(LocalDate::compareTo).orElseThrow() + ".");
            }
            for (LocalDate date : dates) {
                String avant = calendrierActuel.get(date);
                if (avant != null && !nomNormalise(avant).equals(nomNormalise(lue.getNom()))) {
                    details.add("Le " + date + " passe de « " + avant + " » à « " + lue.getNom() + " ».");
                }
            }
            details.add("Les créneaux ne bougent pas : appliquez le calendrier depuis l'écran Journées types.");
            return details;
        }
    }

    /** A refused row, named by the two cells the operator will look for in the spreadsheet. */
    private static LigneImportee refusedRow(CsvParser.Row row, String cle, String libelle, List<String> raisons) {
        return new LigneImportee(
                row.line(), blankAsNull(cle), blankAsNull(libelle), ActionImport.REFUSE, raisons, List.of());
    }

    /** Why a line designates no row, or the same row as a line above. */
    private static void checkKey(Cle cle, Set<String> vus, List<String> raisons) {
        if (cle.refus() != null) {
            raisons.add(cle.refus());
        } else if (!vus.add(cle.cible())) {
            raisons.add("« " + cle.cle() + DEJA_PLUS_HAUT);
        }
    }

    private static void checkKeyAndName(
            Cle cle, String nom, boolean existe, String fiche, Set<String> vus, List<String> raisons) {
        checkKey(cle, vus, raisons);
        if (nom.isBlank() && !existe) {
            raisons.add("La colonne « nom » est vide, et " + fiche + " n'existe pas encore.");
        }
    }

    /** A code no file could cite, or shaped like an id of its referential, refuses the line. */
    private static void checkCode(Cle cle, IdGenerator.Kind kind, List<String> raisons) {
        try {
            Codes.normalise(cle.code(), kind);
        } catch (BusinessError.Invalid e) {
            raisons.add(e.getMessage());
        }
    }

    /**
     * Merges the file's dates into the calendar: a date the file names goes to
     * its template, a date it does not keeps whatever it had.
     *
     * <p>The names are resolved here rather than during the analysis because a
     * template the file creates has no id before it is written — and names are
     * unique, {@link JourneeTypeService#validate} having just enforced it.</p>
     */
    private void mergeCalendrier(Map<String, List<LocalDate>> datesParNom) {
        Map<String, Long> idsParNom = new LinkedHashMap<>();
        journeesTypes
                .list()
                .forEach(journeeType -> idsParNom.put(nomNormalise(journeeType.getNom()), journeeType.getId()));
        Map<LocalDate, Long> calendrier = new TreeMap<>();
        journeesTypes
                .calendrier()
                .forEach(affectation -> calendrier.put(affectation.date(), affectation.journeeTypeId()));
        datesParNom.forEach((nom, dates) -> {
            Long id = idsParNom.get(nom);
            if (id != null) {
                dates.forEach(date -> calendrier.put(date, id));
            }
        });
        List<Affectation> fusionne = new ArrayList<>();
        calendrier.forEach((date, id) -> fusionne.add(new Affectation(date, id)));
        journeesTypes.setCalendrier(fusionne);
    }

    /* --------------------------------- Tools --------------------------------- */

    /** Everything but identity: a file that renames a stand must not erase its schedule. */
    private static Stand copie(Stand source) {
        Stand stand = new Stand();
        stand.setId(source.getId());
        stand.setNom(source.getNom());
        stand.setEmplacement(source.getEmplacement());
        stand.setTypologiesProposees(source.getTypologiesProposees());
        stand.setEffectifMin(source.getEffectifMin());
        stand.setEffectifMax(source.getEffectifMax());
        stand.setReserveMajeurs(source.isReserveMajeurs());
        stand.setPremium(source.isPremium());
        stand.setNiveauEffort(source.getNiveauEffort());
        stand.setHoraires(source.getHoraires());
        stand.setOuvertures(source.getOuvertures());
        stand.setIndisponibilites(source.getIndisponibilites());
        stand.setModifieLe(source.getModifieLe());
        return stand;
    }

    private static List<String> valeursMultiples(String cellule) {
        if (cellule == null || cellule.isBlank()) {
            return List.of();
        }
        return new ArrayList<>(new LinkedHashSet<>(List.of(cellule.split(SEPARATEUR_MULTI))))
                .stream().map(String::trim).filter(valeur -> !valeur.isEmpty()).toList();
    }

    /**
     * How far ahead a two-digit year is read. {@link AnimateurCsvImportService#parseDate}
     * resolves {@code 26} in the hundred years <i>ending</i> with the date it is
     * given, which is right for a birth date and wrong for an edition: handed
     * today, « 10/07/27 » would land in 1927. Given a date eighty-nine years
     * out, the window becomes « the last ten years and the next eighty-nine »,
     * where an event date actually lives.
     */
    private static final int ANNEES_A_VENIR = 89;

    /** A date of the event, in any of the dialects a spreadsheet writes; null and a reason when unreadable. */
    private static LocalDate readEventDate(String cellule, List<String> raisons) {
        String valeur = cellule == null ? "" : cellule.trim();
        if (valeur.isEmpty()) {
            raisons.add("La date est absente.");
            return null;
        }
        LocalDate date = AnimateurCsvImportService.parseDate(
                valeur, LocalDate.now(ZoneId.systemDefault()).plusYears(ANNEES_A_VENIR));
        if (date == null) {
            raisons.add("Date illisible « " + valeur + " » : attendu AAAA-MM-JJ, ou JJ/MM/AAAA.");
        }
        return date;
    }

    /** An hour of the grid, in the compact forms {@link CompactTime} reads; null and a reason when unreadable. */
    private static LocalTime readTime(String cellule, String champ, List<String> raisons) {
        String valeur = cellule == null ? "" : cellule.trim();
        if (valeur.isEmpty()) {
            raisons.add("La colonne « " + champ + " » est vide.");
            return null;
        }
        try {
            return CompactTime.parse(valeur);
        } catch (BusinessError.Invalid e) {
            raisons.add("Colonne « " + champ + " » : " + e.getMessage());
            return null;
        }
    }

    /** {@code 2026-07-10T09:00T12:00}: the natural key of a timeslot, the only thing about it a file can name. */
    private static String creneauKey(LocalDate date, LocalTime debut, LocalTime fin) {
        return date + "T" + debut + "T" + fin;
    }

    /** The hours as the file wrote them, so a refused row is found back in the spreadsheet. */
    private static String libelleHoraire(String debut, String fin) {
        String cellule = (debut == null ? "" : debut.trim()) + "-" + (fin == null ? "" : fin.trim());
        return cellule.equals("-") ? null : cellule;
    }

    /** Two day templates with the same name, however it is cased, are the same template. */
    private static String nomNormalise(String nom) {
        return nom == null ? "" : nom.strip().toLowerCase(Locale.ROOT);
    }

    private static Integer readHeadcount(String cellule, String champ) {
        if (cellule == null || cellule.isBlank()) {
            return null;
        }
        try {
            int valeur = Integer.parseInt(cellule.trim());
            if (valeur < 0) {
                throw new BusinessError.Invalid(champ + " ne peut pas être négatif : « " + cellule.trim() + " ».");
            }
            return valeur;
        } catch (NumberFormatException _) {
            throw new BusinessError.Invalid(champ + " n'est pas un nombre : « " + cellule.trim() + " ».");
        }
    }

    private static Double readCoordinate(String cellule, String champ) {
        if (cellule == null || cellule.isBlank()) {
            return null;
        }
        try {
            return Double.parseDouble(cellule.trim().replace(',', '.'));
        } catch (NumberFormatException _) {
            throw new BusinessError.Invalid(champ + " n'est pas un nombre décimal : « " + cellule.trim() + " ».");
        }
    }

    /** « oui », « true », « x », « 1 » — what a spreadsheet writes in a flag column. */
    private static boolean readFlag(String cellule) {
        String valeur = cellule == null ? "" : cellule.trim().toLowerCase(Locale.ROOT);
        return valeur.equals("oui")
                || valeur.equals("true")
                || valeur.equals("vrai")
                || valeur.equals("x")
                || valeur.equals("1");
    }

    private static String blankAsNull(String valeur) {
        return valeur == null || valeur.isBlank() ? null : valeur;
    }

    private static String groupe(int valeur) {
        return String.format(Locale.ROOT, "%,d", valeur).replace(',', ' ');
    }

    private static void refuseSpreadsheet(String fileName, String content) {
        String nom = fileName == null ? "" : fileName.toLowerCase(Locale.ROOT);
        String texte = content == null ? "" : content;
        if (nom.endsWith(".xlsx")
                || nom.endsWith(".xls")
                || nom.endsWith(".ods")
                || texte.startsWith(ZIP_SIGNATURE)
                || texte.indexOf('\0') >= 0) {
            throw new BusinessError.Invalid("Ce format n'est pas accepté : seul le CSV est lu. Dans votre tableur, "
                    + "choisissez « Enregistrer sous » puis « CSV (séparateur : point-virgule) », et déposez ce "
                    + "fichier-là.");
        }
    }

    /** One write of the analysis, replayed against the service when the operator confirms. */
    @FunctionalInterface
    private interface Ecriture {
        void ecrire(ReferentielCsvImportService service);
    }

    /** Where each awaited column sits, matched on its header whatever its case or accents. */
    private record Colonnes(Map<String, Integer> index) {

        /** « code|id »: either column will do — {@code id} is what a file exported before ADR 0050 carries. */
        private static final Map<ImportTarget, List<String>> REQUISES = Map.of(
                ImportTarget.TYPOLOGIES, List.of("code|id", "libelle"),
                ImportTarget.EMPLACEMENTS, List.of("code|id", "nom"),
                ImportTarget.STANDS, List.of("code|id", "nom", "typologies"),
                ImportTarget.CRENEAUX, List.of("date", "heureDebut", "heureFin"),
                ImportTarget.JOURNEES_TYPES, List.of("nom", "vacations"));

        static Colonnes of(ImportTarget cible, List<String> entetes) {
            Map<String, Integer> index = new LinkedHashMap<>();
            for (int i = 0; i < entetes.size(); i++) {
                index.putIfAbsent(key(entetes.get(i)), i);
            }
            // Named as the operator writes them, matched on their normalised
            // form: « heuredebut, heurefin » is a message nobody can act on.
            List<String> manquantes = REQUISES.get(cible).stream()
                    .filter(colonne -> List.of(colonne.split("\\|")).stream()
                            .noneMatch(alternative -> index.containsKey(key(alternative))))
                    .map(colonne -> colonne.replace("|", " (ou ") + (colonne.contains("|") ? ")" : ""))
                    .toList();
            if (!manquantes.isEmpty()) {
                throw new BusinessError.Invalid(
                        "Colonne(s) absente(s) du fichier : " + String.join(", ", manquantes)
                                + ". La première ligne doit nommer les colonnes ; téléchargez l'exemple pour la forme attendue.");
            }
            return new Colonnes(index);
        }

        String valeur(CsvParser.Row row, String colonne) {
            Integer position = index.get(colonne);
            return position == null ? "" : row.value(position).trim();
        }

        /** `Effectif Min`, `effectif_min` and `EFFECTIFMIN` are the same column. */
        private static String key(String entete) {
            return StandGrilleImportService.normalise(entete).replaceAll("[^a-z0-9]", "");
        }
    }

    /**
     * What the file would do, kept whole so the preview and the write cannot
     * diverge.
     *
     * @param marqueModification whether the write moves data a solve reads, and
     *        the toolbar must therefore warn about. True everywhere but the day
     *        templates: those change nothing until their calendar is applied,
     *        and saying otherwise turns the warning into noise.
     */
    private record Analyse(
            ImportTarget cible,
            CsvParser.Table table,
            List<LigneImportee> lignes,
            List<Ecriture> ecritures,
            List<String> typologiesACreer,
            boolean marqueModification) {

        Analyse(
                ImportTarget cible,
                CsvParser.Table table,
                List<LigneImportee> lignes,
                List<Ecriture> ecritures,
                List<String> typologiesACreer) {
            this(cible, table, lignes, ecritures, typologiesACreer, true);
        }

        ReferentielCsvImportReport report(boolean applied) {
            int refusees = (int) lignes.stream()
                    .filter(ligne -> ligne.action() == ActionImport.REFUSE)
                    .count();
            int creees = (int) lignes.stream()
                    .filter(ligne -> ligne.action() == ActionImport.CREE)
                    .count();
            int misesAJour = (int) lignes.stream()
                    .filter(ligne -> ligne.action() == ActionImport.MIS_A_JOUR)
                    .count();
            return new ReferentielCsvImportReport(
                    applied,
                    cible,
                    table.columns(),
                    String.valueOf(table.separator()),
                    lignes.size(),
                    creees + misesAJour,
                    refusees,
                    creees,
                    misesAJour,
                    typologiesACreer,
                    lignes);
        }
    }
}
