// The créneau form: three fields, and the only entity whose id is generated by
// the server — so what it sends on a creation (no `id`) and on an edit (the
// id it was opened on) is the contract with `ReferenceCrudService`.
//
// Rendered rather than driven through `save()` directly: the `required`
// attributes and the label wiring only exist in the template, and this is the
// file where a claim about them can be checked.

import { provideZonelessChangeDetection, signal } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { NgForm } from '@angular/forms';
import { By } from '@angular/platform-browser';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ReferenceCrudService } from '../../core/reference-crud.service';
import { SolverJobService } from '../../core/solver-job.service';
import { Creneau } from '../../core/models';
import { CreneauFormDialog } from './creneau-form-dialog';

function monter(
  creneau: Creneau | null,
  options: { editingLocked?: boolean; saveOk?: boolean } = {},
) {
  const save = vi.fn(async () => options.saveOk ?? true);
  const close = vi.fn();
  TestBed.resetTestingModule();
  TestBed.configureTestingModule({
    providers: [
      provideZonelessChangeDetection(),
      {
        provide: SolverJobService,
        useValue: { editingLocked: signal(options.editingLocked ?? false) },
      },
      { provide: ReferenceCrudService, useValue: { save } },
      { provide: MatDialogRef, useValue: { close } },
      { provide: MAT_DIALOG_DATA, useValue: { creneau } },
    ],
  });
  return { fixture: TestBed.createComponent(CreneauFormDialog), save, close };
}

function racine(fixture: ComponentFixture<CreneauFormDialog>): HTMLElement {
  return fixture.nativeElement as HTMLElement;
}

function champ(fixture: ComponentFixture<CreneauFormDialog>, name: string): HTMLInputElement {
  return racine(fixture).querySelector(`input[name="${name}"]`) as HTMLInputElement;
}

function saisir(fixture: ComponentFixture<CreneauFormDialog>, name: string, valeur: string): void {
  const input = champ(fixture, name);
  input.value = valeur;
  input.dispatchEvent(new Event('input'));
}

function submit(fixture: ComponentFixture<CreneauFormDialog>): void {
  racine(fixture).querySelector('form')!.dispatchEvent(new Event('submit'));
}

/** Payload of the single `crud.save` call, as the service received it. */
function payload(save: ReturnType<typeof vi.fn>): Partial<Creneau> {
  return (save.mock.calls[0] as unknown as [string, Partial<Creneau>])[1];
}

const CRENEAU: Creneau = {
  id: 7,
  jour: 1,
  date: '2026-07-14',
  heureDebut: '10:00',
  heureFin: '12:00',
};

describe('CreneauFormDialog', () => {
  let erreursConsole: unknown[][];

  beforeEach(() => {
    erreursConsole = [];
    vi.spyOn(console, 'error').mockImplementation((...args: unknown[]) =>
      erreursConsole.push(args),
    );
  });

  it('names every control, so the labels render and no NG01352 is thrown', async () => {
    const { fixture } = monter(null);
    await fixture.whenStable();

    const ngForm = fixture.debugElement.query(By.directive(NgForm)).injector.get(NgForm);
    expect(Object.keys(ngForm.controls).sort((a, b) => a.localeCompare(b))).toEqual([
      'couverturePause',
      'date',
      'heureDebut',
      'heureFin',
    ]);
    expect(erreursConsole.filter((args) => JSON.stringify(args).includes('NG01352'))).toEqual([]);
  });

  it('fills the three fields from the créneau it was opened on', async () => {
    const { fixture } = monter(CRENEAU);
    await fixture.whenStable();

    expect(champ(fixture, 'date').value).toBe('2026-07-14');
    expect(champ(fixture, 'heureDebut').value).toBe('10:00');
    expect(champ(fixture, 'heureFin').value).toBe('12:00');
    expect(racine(fixture).querySelector('h2')!.textContent!.trim()).toBe(
      'Modifier le créneau du 2026-07-14 10:00',
    );
  });

  it('starts empty on a creation and offers to create', async () => {
    const { fixture } = monter(null);
    await fixture.whenStable();

    expect(champ(fixture, 'date').value).toBe('');
    expect(racine(fixture).querySelector('h2')!.textContent!.trim()).toBe('Nouveau créneau');
    expect(racine(fixture).querySelector('button[type="submit"]')!.textContent!).toContain(
      'Créer le créneau',
    );
  });

  it('sends no id on a creation, and lets the server generate it', async () => {
    const { fixture, save, close } = monter(null);
    await fixture.whenStable();

    saisir(fixture, 'date', '2026-07-15');
    saisir(fixture, 'heureDebut', '14:00');
    saisir(fixture, 'heureFin', '19:00');
    await fixture.whenStable();
    submit(fixture);
    await fixture.whenStable();

    expect(save).toHaveBeenCalledOnce();
    expect(payload(save)).toEqual({
      date: '2026-07-15',
      heureDebut: '14:00',
      heureFin: '19:00',
      couverturePause: false,
      modifieLe: null,
    });
    const [, , editingId] = save.mock.calls[0] as unknown as [
      string,
      Partial<Creneau>,
      number | null,
    ];
    expect(editingId).toBeNull();
    expect(close).toHaveBeenCalledWith(true);
  });

  it('sends the id it was opened on when editing', async () => {
    const { fixture, save } = monter(CRENEAU);
    await fixture.whenStable();

    saisir(fixture, 'heureFin', '13:00');
    await fixture.whenStable();
    submit(fixture);
    await fixture.whenStable();

    expect(payload(save)).toEqual({
      id: 7,
      date: '2026-07-14',
      heureDebut: '10:00',
      heureFin: '13:00',
      couverturePause: false,
      modifieLe: null,
    });
    expect((save.mock.calls[0] as unknown as [string, unknown, number])[2]).toBe(7);
  });

  it('keeps the dialog open when the save is refused', async () => {
    const { fixture, close } = monter(CRENEAU, { saveOk: false });
    await fixture.whenStable();

    submit(fixture);
    await fixture.whenStable();

    expect(close).not.toHaveBeenCalled();
  });

  it('cancels without saving', async () => {
    const { fixture, save, close } = monter(CRENEAU);
    await fixture.whenStable();

    (racine(fixture).querySelector('mat-dialog-actions button') as HTMLButtonElement).click();

    expect(save).not.toHaveBeenCalled();
    expect(close).toHaveBeenCalledWith(false);
  });

  it('disables the whole form and says why while a solve is running', async () => {
    const { fixture } = monter(CRENEAU, { editingLocked: true });
    await fixture.whenStable();

    expect(racine(fixture).querySelector('.locked-hint')).not.toBeNull();
    expect((racine(fixture).querySelector('fieldset') as HTMLFieldSetElement).disabled).toBe(true);
    expect(
      (racine(fixture).querySelector('button[type="submit"]') as HTMLButtonElement).disabled,
    ).toBe(true);
  });

  // The three `required` attributes used to be decorative: `(ngSubmit)` fires
  // whatever the form's validity, so an empty créneau reached the server, whose
  // NOT NULL columns rejected it — « Saisie refusée » instead of an error
  // against the field.
  it('refuses to submit an empty créneau', async () => {
    const { fixture, save } = monter(null);
    await fixture.whenStable();

    expect(
      (racine(fixture).querySelector('button[type="submit"]') as HTMLButtonElement).disabled,
    ).toBe(true);

    submit(fixture);
    await fixture.whenStable();

    expect(save).not.toHaveBeenCalled();
  });

  // An end at or before the start is not a mistake to refuse: it is how the
  // domain writes a slot running past midnight — `Creneau.getDureeMinutes`
  // counts 20:00→00:00 as 240 minutes, `CreneauGridServiceTest` slices such a
  // « nuit », and only such a slot reads a stand window dated J+1. The form
  // names the case so a typo is caught by the person who made it, and saves it.
  it('accepts a créneau running past midnight, and names the case', async () => {
    const { fixture, save } = monter(null);
    await fixture.whenStable();

    saisir(fixture, 'date', '2026-07-08');
    saisir(fixture, 'heureDebut', '20:00');
    saisir(fixture, 'heureFin', '00:00');
    await fixture.whenStable();

    expect(racine(fixture).textContent).toContain('franchit minuit');
    expect(
      (racine(fixture).querySelector('button[type="submit"]') as HTMLButtonElement).disabled,
    ).toBe(false);

    submit(fixture);
    await fixture.whenStable();

    expect(payload(save)).toEqual({
      date: '2026-07-08',
      heureDebut: '20:00',
      heureFin: '00:00',
      couverturePause: false,
      modifieLe: null,
    });
  });

  // The server writes `couverture_pause` from the body unconditionally, and the
  // form used to send a body without it: editing the hours of a slot generated
  // under EFFECTIF_REDUIT reset the flag, and the stands went back to full
  // headcount on the next solve. The flag has to survive an edit it is not
  // about.
  it('keeps the pause-coverage flag of the slot it edits', async () => {
    const { fixture, save } = monter({ ...CRENEAU, couverturePause: true });
    await fixture.whenStable();

    saisir(fixture, 'heureFin', '13:00');
    await fixture.whenStable();
    submit(fixture);
    await fixture.whenStable();

    expect(payload(save)).toMatchObject({ id: 7, heureFin: '13:00', couverturePause: true });
  });

  it('declares a meal relay from the checkbox', async () => {
    const { fixture, save } = monter(CRENEAU);
    await fixture.whenStable();

    const checkbox = racine(fixture).querySelector(
      'mat-checkbox[name="couverturePause"] input',
    ) as HTMLInputElement;
    expect(checkbox.checked).toBe(false);
    checkbox.click();
    await fixture.whenStable();
    submit(fixture);
    await fixture.whenStable();

    expect(payload(save)).toMatchObject({ id: 7, couverturePause: true });
  });

  it('says nothing about midnight for a slot that stays inside its day', async () => {
    const { fixture } = monter(null);
    await fixture.whenStable();

    saisir(fixture, 'date', '2026-07-08');
    saisir(fixture, 'heureDebut', '09:00');
    saisir(fixture, 'heureFin', '18:00');
    await fixture.whenStable();

    expect(racine(fixture).textContent).not.toContain('franchit minuit');
  });
});
