-- Every business id becomes generated by the application instead of chosen
-- by the user (ADR 0050). Five referentials draw from a counter of their
-- own edition — A1, A2… for animateurs, S… for stands, T… for typologies,
-- L… for emplacements, C… for ad hoc constraints — and editions from a
-- global sequence (E1, E2…). The columns stay TEXT: only the values change.
--
-- The existing rows are renumbered: an id typed by hand (`marie.dupont`) or
-- derived from a name (the CSV import's `marie-dupont`) is personal data
-- that left through every MCP answer. An id that already has the shape of
-- its referential's (`A12` for an animateur, `S3` for a stand) keeps its
-- value — it names nobody, and every file citing it keeps working — and the
-- others are numbered after the highest such number. Stands, typologies and
-- emplacements keep a renumbered id as their `code`, the readable key the
-- import files match on; a code never has the shape of an id of its own
-- referential, so « an id or a code » is never ambiguous.
--
-- IRREVERSIBLE, and a MAJOR version: a dump taken before this migration does
-- not restore after it. Take a backup first.
--
-- The rewrite is explicit rather than cascaded: every foreign key of the
-- schema is dropped, every column carrying one of the six tables'
-- ids is rewritten through a mapping table, and the keys are recreated from
-- their saved definitions. A cascade would have covered the declared keys
-- only, and the dangerous columns are precisely the ones without one (the
-- snapshots' JSONB, the notification keys, the journal, the solver queue).
--
-- A value naming a row that no longer exists (a deleted animateur in an old
-- snapshot or journal line) is replaced by an orphan marker, `~` followed by
-- a hash: kept, it could name the newcomer who draws the same number — and
-- it may be the very name this migration exists to remove.

-- 1. Helpers, dropped at the end.

-- The order NaturalOrder.OF_IDS sorts ids in (A2 before A10), which is the
-- order the solver's value ranges were built in: numbering in that order
-- keeps the search path as close as possible to the one before.
CREATE FUNCTION migration_cle_naturelle(valeur TEXT) RETURNS TEXT
    LANGUAGE sql IMMUTABLE AS $$
    SELECT COALESCE(string_agg(
                        CASE WHEN morceau[1] ~ '^[0-9]'
                             THEN lpad(COALESCE(NULLIF(ltrim(morceau[1], '0'), ''), '0'), 40, '0')
                             ELSE morceau[1] END,
                        '' ORDER BY rang), '')
    FROM regexp_matches(valeur, '([0-9]+|[^0-9]+)', 'g') WITH ORDINALITY AS m(morceau, rang)
$$;

CREATE FUNCTION migration_orphelin(valeur TEXT) RETURNS TEXT
    LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE WHEN valeur IS NULL THEN NULL ELSE '~' || left(md5(valeur), 12) END
$$;

-- 2. The readable code of stands, typologies and emplacements, seeded with
--    the old id of every row about to be renumbered, so the files the
--    organisers keep still match.

ALTER TABLE stand ADD COLUMN code VARCHAR(64);
ALTER TABLE typologie ADD COLUMN code VARCHAR(64);
ALTER TABLE emplacement ADD COLUMN code VARCHAR(64);
UPDATE stand SET code = id WHERE id !~ '^S[1-9][0-9]*$';
UPDATE typologie SET code = id WHERE id !~ '^T[1-9][0-9]*$';
UPDATE emplacement SET code = id WHERE id !~ '^L[1-9][0-9]*$';

-- 3. The mapping, old id → new id. Editions carry '' as their edition_id.

CREATE TABLE migration_remap (
    entite     VARCHAR(16) NOT NULL,
    edition_id VARCHAR(64) NOT NULL,
    ancien     VARCHAR(64) NOT NULL,
    nouveau    VARCHAR(64) NOT NULL,
    PRIMARY KEY (entite, edition_id, ancien)
);

-- An id of the referential's own shape is kept; the others follow the
-- highest such number of their edition, in natural order.
CREATE FUNCTION migration_numeroter(table_nom TEXT, entite TEXT, prefixe TEXT) RETURNS VOID
    LANGUAGE plpgsql AS $$
BEGIN
    EXECUTE format(
        'INSERT INTO migration_remap (entite, edition_id, ancien, nouveau) '
            || 'SELECT %2$L, t.edition_id, t.id, '
            || '       CASE WHEN t.id ~ %4$L THEN t.id '
            || '            ELSE %3$L || (COALESCE(b.base, 0) + row_number() OVER ('
            || '                PARTITION BY t.edition_id, t.id ~ %4$L '
            || '                ORDER BY migration_cle_naturelle(t.id) COLLATE "C", t.id COLLATE "C")) END '
            || 'FROM %1$I t '
            || 'LEFT JOIN (SELECT edition_id, MAX(CAST(substr(id, 2) AS BIGINT)) AS base FROM %1$I '
            || '           WHERE id ~ %4$L GROUP BY edition_id) b ON b.edition_id = t.edition_id',
        table_nom, entite, prefixe, '^' || prefixe || '[1-9][0-9]*$');
END
$$;

SELECT migration_numeroter('animateur', 'ANIMATEUR', 'A');
SELECT migration_numeroter('stand', 'STAND', 'S');
SELECT migration_numeroter('typologie', 'TYPOLOGIE', 'T');
SELECT migration_numeroter('emplacement', 'EMPLACEMENT', 'L');
SELECT migration_numeroter('contrainte_ad_hoc', 'CONTRAINTE', 'C');

INSERT INTO migration_remap (entite, edition_id, ancien, nouveau)
SELECT 'EDITION', '', e.id,
       CASE WHEN e.id ~ '^E[1-9][0-9]*$' THEN e.id
            ELSE 'E' || (COALESCE(b.base, 0) + row_number() OVER (
                PARTITION BY e.id ~ '^E[1-9][0-9]*$' ORDER BY e.cree_le, e.id COLLATE "C")) END
FROM edition e
CROSS JOIN (SELECT MAX(CAST(substr(id, 2) AS BIGINT)) AS base FROM edition WHERE id ~ '^E[1-9][0-9]*$') b;

-- 4. Drop every foreign key of the schema, keeping its definition to
--    recreate it verbatim once the values agree again. Not only those
--    pointing at the six tables: edition_id is part of nearly every
--    composite key (publication_destinataire → plan_snapshot, …).

CREATE TABLE migration_cle_etrangere (
    table_nom  TEXT NOT NULL,
    contrainte TEXT NOT NULL,
    definition TEXT NOT NULL
);

INSERT INTO migration_cle_etrangere (table_nom, contrainte, definition)
SELECT conrelid::regclass::TEXT, conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE contype = 'f'
  AND connamespace = current_schema()::regnamespace;

DO $$
DECLARE
    cle RECORD;
BEGIN
    FOR cle IN SELECT table_nom, contrainte FROM migration_cle_etrangere LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', cle.table_nom, cle.contrainte);
    END LOOP;
END
$$;

-- 5. Rewrite one column through the mapping. Two passes: the first marks
--    every rewritten value with a leading \x01, so that no row ever takes a
--    value another row of the same table still holds (a primary key is
--    checked row by row); the second strips the mark. A value the mapping
--    does not know becomes an orphan marker when `orphelins` says the
--    column may hold one — only columns without a foreign key can.

CREATE FUNCTION migration_reecrire(table_nom TEXT, colonne TEXT, entite TEXT, orphelins BOOLEAN)
    RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    EXECUTE format(
        'UPDATE %1$I t SET %2$I = chr(1) || r.nouveau FROM migration_remap r '
            || 'WHERE r.entite = %3$L AND r.edition_id = t.edition_id AND r.ancien = t.%2$I',
        table_nom, colonne, entite);
    IF orphelins THEN
        EXECUTE format(
            'UPDATE %1$I SET %2$I = chr(1) || migration_orphelin(%2$I) '
                || 'WHERE %2$I IS NOT NULL AND left(%2$I, 1) <> chr(1)',
            table_nom, colonne);
    END IF;
    EXECUTE format('UPDATE %1$I SET %2$I = substr(%2$I, 2) WHERE left(%2$I, 1) = chr(1)', table_nom, colonne);
END
$$;

SELECT migration_reecrire('animateur', 'id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('animateur_competence', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('animateur_jour_indispo', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('animateur_souhait', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('confirmation_planning', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('contrainte_animateur', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('declaration_disponibilite', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('demande_echange', 'demandeur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('demande_echange', 'cible_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('espace_acces', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('espace_session', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('poste_affectation', 'animateur_id', 'ANIMATEUR', FALSE);
SELECT migration_reecrire('verrouillage_planning', 'animateur_id', 'ANIMATEUR', FALSE);
-- Without a foreign key: the trace of who a publication was sent to, and
-- who a scheduled notification was for.
SELECT migration_reecrire('publication_destinataire', 'animateur_id', 'ANIMATEUR', TRUE);
SELECT migration_reecrire('notification_planifiee', 'animateur_id', 'ANIMATEUR', TRUE);

SELECT migration_reecrire('stand', 'id', 'STAND', FALSE);
SELECT migration_reecrire('consigne_edition_ouverture', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('contrainte_ad_hoc', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('creneau_stand_ouvert', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('demande_echange', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('poste_affectation', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('stand_horaire', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('stand_indisponibilite', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('stand_ouverture', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('stand_typologie', 'stand_id', 'STAND', FALSE);
SELECT migration_reecrire('verrouillage_planning', 'stand_id', 'STAND', FALSE);
-- The stand a directed swap request aims at carries no foreign key (V46).
SELECT migration_reecrire('demande_echange', 'stand_cible_id', 'STAND', TRUE);

SELECT migration_reecrire('typologie', 'id', 'TYPOLOGIE', FALSE);
SELECT migration_reecrire('animateur_competence', 'typologie', 'TYPOLOGIE', FALSE);
SELECT migration_reecrire('animateur_souhait', 'typologie', 'TYPOLOGIE', FALSE);
SELECT migration_reecrire('stand_typologie', 'typologie', 'TYPOLOGIE', FALSE);

SELECT migration_reecrire('emplacement', 'id', 'EMPLACEMENT', FALSE);
SELECT migration_reecrire('stand', 'emplacement_id', 'EMPLACEMENT', FALSE);

SELECT migration_reecrire('contrainte_ad_hoc', 'id', 'CONTRAINTE', FALSE);
SELECT migration_reecrire('contrainte_animateur', 'contrainte_id', 'CONTRAINTE', FALSE);

-- 6. The ids no foreign key declares, inside text and JSONB.

-- A pending availability declaration lists the typologies wished for, one
-- id per line: a line naming a deleted typologie keeps being ignored the
-- way it was, as an orphan.
UPDATE declaration_disponibilite d
SET souhaits = (
    SELECT string_agg(COALESCE(r.nouveau, migration_orphelin(ligne)), E'\n' ORDER BY rang)
    FROM unnest(string_to_array(d.souhaits, E'\n')) WITH ORDINALITY AS s(ligne, rang)
    LEFT JOIN migration_remap r
           ON r.entite = 'TYPOLOGIE' AND r.edition_id = d.edition_id AND r.ancien = s.ligne)
WHERE souhaits IS NOT NULL AND souhaits <> '';

-- The notification keys `animateurId|date` and `animateurId|publicationInstant`:
-- left untouched, the next run would find no key and write to everybody again.
-- ALERTE_ECHANGE keys on a swap request's UUID, which does not move.
UPDATE notification_planifiee n
SET cle = chr(1) || COALESCE(r.nouveau, migration_orphelin(split.animateur)) || split.suite
FROM (SELECT edition_id, type, cle,
             regexp_replace(cle, '\|[^|]*$', '') AS animateur,
             substring(cle FROM '\|[^|]*$') AS suite
      FROM notification_planifiee
      WHERE type <> 'ALERTE_ECHANGE' AND cle LIKE '%|%') AS split
LEFT JOIN migration_remap r
       ON r.entite = 'ANIMATEUR' AND r.edition_id = split.edition_id AND r.ancien = split.animateur
WHERE n.edition_id = split.edition_id AND n.type = split.type AND n.cle = split.cle;
UPDATE notification_planifiee SET cle = substr(cle, 2) WHERE left(cle, 1) = chr(1);

-- A snapshot's seats name their stand and animateur. The published plan is
-- what stabiliteDuPlanPublie joins the current one against: a snapshot left
-- on the old ids would read as a plan in which every seat moved.
UPDATE plan_snapshot s
SET contenu = (
    SELECT COALESCE(jsonb_agg(
               siege
                   || CASE WHEN siege ? 'standId' AND jsonb_typeof(siege -> 'standId') = 'string'
                           THEN jsonb_build_object('standId',
                                    COALESCE(rs.nouveau, migration_orphelin(siege ->> 'standId')))
                           ELSE '{}'::jsonb END
                   || CASE WHEN siege ? 'animateurId' AND jsonb_typeof(siege -> 'animateurId') = 'string'
                           THEN jsonb_build_object('animateurId',
                                    COALESCE(ra.nouveau, migration_orphelin(siege ->> 'animateurId')))
                           ELSE '{}'::jsonb END
               ORDER BY rang), '[]'::jsonb)
    FROM jsonb_array_elements(s.contenu) WITH ORDINALITY AS e(siege, rang)
    LEFT JOIN migration_remap rs
           ON rs.entite = 'STAND' AND rs.edition_id = s.edition_id AND rs.ancien = siege ->> 'standId'
    LEFT JOIN migration_remap ra
           ON ra.entite = 'ANIMATEUR' AND ra.edition_id = s.edition_id AND ra.ancien = siege ->> 'animateurId')
WHERE contenu IS NOT NULL AND jsonb_typeof(contenu) = 'array';

-- A queued solve is replayed at startup with its perimeter: left on the old
-- ids it would target nobody.
UPDATE solver_job j
SET perimetre = j.perimetre
    || CASE WHEN jsonb_typeof(j.perimetre -> 'animateurIds') = 'array'
            THEN jsonb_build_object('animateurIds', (
                SELECT COALESCE(jsonb_agg(COALESCE(r.nouveau, migration_orphelin(v)) ORDER BY rang), '[]'::jsonb)
                FROM jsonb_array_elements_text(j.perimetre -> 'animateurIds') WITH ORDINALITY AS e(v, rang)
                LEFT JOIN migration_remap r
                       ON r.entite = 'ANIMATEUR' AND r.edition_id = j.edition_id AND r.ancien = v))
            ELSE '{}'::jsonb END
    || CASE WHEN jsonb_typeof(j.perimetre -> 'standIds') = 'array'
            THEN jsonb_build_object('standIds', (
                SELECT COALESCE(jsonb_agg(COALESCE(r.nouveau, migration_orphelin(v)) ORDER BY rang), '[]'::jsonb)
                FROM jsonb_array_elements_text(j.perimetre -> 'standIds') WITH ORDINALITY AS e(v, rang)
                LEFT JOIN migration_remap r
                       ON r.entite = 'STAND' AND r.edition_id = j.edition_id AND r.ancien = v))
            ELSE '{}'::jsonb END
WHERE perimetre IS NOT NULL AND jsonb_typeof(perimetre) = 'object';

-- The journal records ids only, and resolves names at read time: its lines
-- must follow the rows they name. The entity type says which mapping
-- applies (AJUSTEMENT is an ad hoc constraint); an actor id is an
-- animateur's only when the actor is one.
UPDATE journal_action j
SET entite_id = COALESCE(
        (SELECT r.nouveau FROM migration_remap r
         WHERE r.entite = CASE j.entite WHEN 'AJUSTEMENT' THEN 'CONTRAINTE' ELSE j.entite END
           AND r.edition_id = j.edition_id AND r.ancien = j.entite_id),
        migration_orphelin(j.entite_id))
WHERE j.entite IN ('ANIMATEUR', 'STAND', 'TYPOLOGIE', 'EMPLACEMENT', 'AJUSTEMENT')
  AND j.entite_id IS NOT NULL;

UPDATE journal_action j
SET acteur_id = COALESCE(
        (SELECT r.nouveau FROM migration_remap r
         WHERE r.entite = 'ANIMATEUR' AND r.edition_id = j.edition_id AND r.ancien = j.acteur_id),
        migration_orphelin(j.acteur_id))
WHERE j.acteur = 'ANIMATEUR' AND j.acteur_id IS NOT NULL;

UPDATE journal_action j
SET entite_id = COALESCE(
        (SELECT r.nouveau FROM migration_remap r
         WHERE r.entite = 'EDITION' AND r.ancien = j.entite_id),
        migration_orphelin(j.entite_id))
WHERE j.entite = 'EDITION' AND j.entite_id IS NOT NULL;

-- 7. The editions last: every other mapping is keyed on the old edition id.
--    Every column named edition_id is rewritten, with or without a foreign
--    key (kpi_historique has none, and outlives a deleted edition), and
--    loses its default.

UPDATE edition e
SET id = chr(1) || r.nouveau
FROM migration_remap r
WHERE r.entite = 'EDITION' AND r.ancien = e.id;
UPDATE edition SET id = substr(id, 2) WHERE left(id, 1) = chr(1);

DO $$
DECLARE
    colonne RECORD;
BEGIN
    FOR colonne IN
        SELECT c.table_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema AND t.table_name = c.table_name AND t.table_type = 'BASE TABLE'
        WHERE c.table_schema = current_schema()
          AND c.column_name = 'edition_id'
          AND c.table_name NOT IN ('migration_remap')
    LOOP
        EXECUTE format(
            'UPDATE %1$I t SET edition_id = chr(1) || COALESCE('
                || '(SELECT r.nouveau FROM migration_remap r WHERE r.entite = ''EDITION'' AND r.ancien = t.edition_id), '
                || 'migration_orphelin(t.edition_id)) WHERE t.edition_id IS NOT NULL',
            colonne.table_name);
        EXECUTE format('UPDATE %1$I SET edition_id = substr(edition_id, 2) WHERE left(edition_id, 1) = chr(1)',
            colonne.table_name);
        -- Many tables still default to V30's 'DEFAUT', an edition that no
        -- longer exists: a row inserted without its edition must fail loudly.
        EXECUTE format('ALTER TABLE %I ALTER COLUMN edition_id DROP DEFAULT', colonne.table_name);
    END LOOP;
END
$$;

-- 8. The foreign keys, back as they were.

DO $$
DECLARE
    cle RECORD;
BEGIN
    FOR cle IN SELECT table_nom, contrainte, definition FROM migration_cle_etrangere LOOP
        EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s', cle.table_nom, cle.contrainte, cle.definition);
    END LOOP;
END
$$;

-- 9. The counters. One row per edition and referential, holding the last
--    number handed out: the application increments it under the row's lock
--    (UPDATE … RETURNING), so two concurrent creations never draw the same
--    id, and a number freed by a deletion is never handed out again — a
--    journal line or a snapshot naming it keeps naming the row it named.

CREATE TABLE compteur_identifiant (
    edition_id VARCHAR(64) NOT NULL REFERENCES edition (id) ON DELETE CASCADE,
    entite     VARCHAR(16) NOT NULL,
    dernier    BIGINT      NOT NULL,
    PRIMARY KEY (edition_id, entite),
    CONSTRAINT compteur_identifiant_entite_check
        CHECK (entite IN ('ANIMATEUR', 'STAND', 'TYPOLOGIE', 'EMPLACEMENT', 'CONTRAINTE')),
    CONSTRAINT compteur_identifiant_dernier_check CHECK (dernier >= 0)
);

INSERT INTO compteur_identifiant (edition_id, entite, dernier)
SELECT e.nouveau, r.entite, MAX(CAST(substr(r.nouveau, 2) AS BIGINT))
FROM migration_remap r
JOIN migration_remap e ON e.entite = 'EDITION' AND e.ancien = r.edition_id
WHERE r.entite <> 'EDITION'
GROUP BY e.nouveau, r.entite;

CREATE SEQUENCE edition_numero_seq;
SELECT setval('edition_numero_seq', COALESCE(MAX(CAST(substr(id, 2) AS BIGINT)), 1), COUNT(*) > 0) FROM edition;

-- 10. A code designates one row of its edition, so a file can match on it.

CREATE UNIQUE INDEX ux_stand_code ON stand (edition_id, code);
CREATE UNIQUE INDEX ux_typologie_code ON typologie (edition_id, code);
CREATE UNIQUE INDEX ux_emplacement_code ON emplacement (edition_id, code);

DROP FUNCTION migration_reecrire(TEXT, TEXT, TEXT, BOOLEAN);
DROP FUNCTION migration_numeroter(TEXT, TEXT, TEXT);
DROP FUNCTION migration_orphelin(TEXT);
DROP FUNCTION migration_cle_naturelle(TEXT);
DROP TABLE migration_cle_etrangere;
DROP TABLE migration_remap;
