-- Replaces creneau's user-entered VARCHAR id with a DB-generated numeric
-- surrogate id, and drops the stored `jour` column (now computed at read
-- time from the group's earliest date, never persisted — see
-- Creneau.assignerJours / ReferenceDataRepository.listCreneaux).
--
-- Approach: add a new bigint identity column, backfill every FK that
-- pointed at the old varchar id via a join, then swap the columns and
-- constraints. All existing rows/relationships are preserved; only the
-- id *values* change (from "J1-MATIN" etc. to 1, 2, 3, ...).
--
-- The identity column is GENERATED BY DEFAULT (not ALWAYS): DatabaseDumpService
-- replays SQL dumps as literal INSERT ... VALUES (<id>, ...) statements, which
-- would fail against an ALWAYS identity column without OVERRIDING SYSTEM VALUE.

-- 1. New surrogate id column on creneau.
ALTER TABLE creneau ADD COLUMN id_new BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2. New FK columns on every table that referenced creneau(id).
ALTER TABLE poste_affectation ADD COLUMN creneau_id_new BIGINT;
ALTER TABLE contrainte_ad_hoc ADD COLUMN creneau_id_new BIGINT;
ALTER TABLE creneau_stand_ouvert ADD COLUMN creneau_id_new BIGINT;

-- 3. Backfill children from the join on the old varchar id.
UPDATE poste_affectation pa
   SET creneau_id_new = c.id_new
  FROM creneau c
 WHERE pa.creneau_id = c.id;

UPDATE contrainte_ad_hoc cah
   SET creneau_id_new = c.id_new
  FROM creneau c
 WHERE cah.creneau_id = c.id;

UPDATE creneau_stand_ouvert cso
   SET creneau_id_new = c.id_new
  FROM creneau c
 WHERE cso.creneau_id = c.id;

-- 4. Drop the old varchar FK columns/constraints and the old PK, then
--    rename the new columns into place.
ALTER TABLE poste_affectation DROP COLUMN creneau_id;
ALTER TABLE contrainte_ad_hoc DROP COLUMN creneau_id;
ALTER TABLE creneau_stand_ouvert DROP COLUMN creneau_id;

ALTER TABLE creneau DROP CONSTRAINT creneau_pkey;
ALTER TABLE creneau DROP COLUMN id;
ALTER TABLE creneau DROP COLUMN jour;

ALTER TABLE creneau RENAME COLUMN id_new TO id;
ALTER TABLE creneau ADD PRIMARY KEY (id);

ALTER TABLE poste_affectation RENAME COLUMN creneau_id_new TO creneau_id;
ALTER TABLE poste_affectation ALTER COLUMN creneau_id SET NOT NULL;
ALTER TABLE poste_affectation
    ADD CONSTRAINT poste_affectation_creneau_id_fkey
    FOREIGN KEY (creneau_id) REFERENCES creneau(id);

ALTER TABLE contrainte_ad_hoc RENAME COLUMN creneau_id_new TO creneau_id;
ALTER TABLE contrainte_ad_hoc
    ADD CONSTRAINT contrainte_ad_hoc_creneau_id_fkey
    FOREIGN KEY (creneau_id) REFERENCES creneau(id) ON DELETE SET NULL;

ALTER TABLE creneau_stand_ouvert RENAME COLUMN creneau_id_new TO creneau_id;
ALTER TABLE creneau_stand_ouvert ALTER COLUMN creneau_id SET NOT NULL;
ALTER TABLE creneau_stand_ouvert
    ADD CONSTRAINT creneau_stand_ouvert_creneau_id_fkey
    FOREIGN KEY (creneau_id) REFERENCES creneau(id) ON DELETE CASCADE;
ALTER TABLE creneau_stand_ouvert
    ADD PRIMARY KEY (creneau_id, stand_id);

-- 5. Resync the identity sequence past whatever ids exist right now
--    (fresh installs have none; upgraded installs get non-1-based ids from
--    the backfill above, in insertion order of the old rows).
SELECT setval(pg_get_serial_sequence('creneau', 'id'),
              COALESCE((SELECT MAX(id) FROM creneau), 1), true);
