-- Premier lot du passage des identifiants métier en identités générées par la
-- base (docs/decisions/0049-identifiants-metier-generes-par-la-base.md).
--
-- L'emplacement ouvre le chantier parce qu'il est le référentiel le plus
-- simple : une seule clé étrangère entrante (`stand.emplacement_id`), aucun
-- porteur enfoui dans une charge utile, et le seul porteur sans clé étrangère
-- est la colonne polymorphe du journal. Ce que cette migration valide, c'est
-- le patron — les cinq étapes que les cinq lots suivants rejoueront.
--
-- L'ancien id tapé devient le `code` de la décision D2. Ce n'est pas une
-- commodité : c'est ce qui laisse relisibles les fichiers déjà préparés — la
-- colonne `emplacementId` des imports CSV, la grille des ouvertures, les
-- fichiers scénario — qui citent tous `PLACE-DRAPEAU` et non un numéro. Le
-- code est facultatif pour les lignes futures, mais aucune ligne existante
-- n'en est privée : elle en avait forcément un, c'était sa clé.

/* --------- 1. La nouvelle colonne, qui renumérote en s'ajoutant --------- */

-- GENERATED BY DEFAULT, jamais ALWAYS : une sauvegarde réinsère ses ids
-- littéraux, et ALWAYS les refuserait (D1).
ALTER TABLE emplacement ADD COLUMN id_nouveau BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Les anciens ids n'étaient uniques qu'au sein d'une édition : le PLACE-DRAPEAU
-- de 2025 et celui de 2026 sont deux lignes, et reçoivent bien deux numéros.

/* --------- 2. Le code métier de D2, repris de l'ancien id --------- */

ALTER TABLE emplacement ADD COLUMN code VARCHAR(64);
UPDATE emplacement SET code = id;

-- Unique par édition à la casse près, et seulement quand il est renseigné :
-- un index partiel, pour que plusieurs emplacements sans code cohabitent.
CREATE UNIQUE INDEX emplacement_code_unique
    ON emplacement (edition_id, UPPER(code))
    WHERE code IS NOT NULL;

/* --------- 3. La table de correspondance --------- */

-- Clée sur le COUPLE, jamais sur le seul ancien id : une jointure qui
-- l'oublierait rendrait deux lignes pour chaque PLACE-DRAPEAU et mélangerait
-- les éditions. C'est le patron `creneau_remap` de la duplication d'édition,
-- avec la colonne d'édition en plus — le créneau, lui, était déjà unique.
CREATE TEMPORARY TABLE emplacement_remap (
    edition_id VARCHAR(64) NOT NULL,
    ancien_id  VARCHAR(64) NOT NULL,
    nouvel_id  BIGINT      NOT NULL,
    PRIMARY KEY (edition_id, ancien_id)
) ON COMMIT DROP;

INSERT INTO emplacement_remap (edition_id, ancien_id, nouvel_id)
SELECT edition_id, id, id_nouveau FROM emplacement;

/* --------- 4. La clé étrangère entrante --------- */

ALTER TABLE stand DROP CONSTRAINT IF EXISTS stand_emplacement_fkey;
ALTER TABLE stand DROP CONSTRAINT IF EXISTS stand_edition_id_emplacement_id_fkey;

ALTER TABLE stand ADD COLUMN emplacement_id_nouveau BIGINT;
UPDATE stand s
   SET emplacement_id_nouveau = r.nouvel_id
  FROM emplacement_remap r
 WHERE r.edition_id = s.edition_id
   AND r.ancien_id = s.emplacement_id;

ALTER TABLE stand DROP COLUMN emplacement_id;
ALTER TABLE stand RENAME COLUMN emplacement_id_nouveau TO emplacement_id;

/* --------- 5. Les porteurs sans clé étrangère --------- */

-- `journal_action.entite_id` est polymorphe : le genre est dans « entite »,
-- donc la réécriture se fait une valeur de cette colonne à la fois, jamais en
-- aveugle. Sans elle, l'historique cesse de résoudre le nom des lignes
-- passées. Le journal n'a pas de clé étrangère vers le référentiel — il
-- survit à la suppression de ce qu'il nomme —, d'où la jointure et non une
-- cascade.
UPDATE journal_action j
   SET entite_id = r.nouvel_id::text
  FROM emplacement_remap r
 WHERE j.entite = 'EMPLACEMENT'
   AND r.edition_id = j.edition_id
   AND r.ancien_id = j.entite_id;

-- Aucune charge utile ne porte d'id d'emplacement : `plan_snapshot.contenu`
-- nomme des stands, des animateurs et des créneaux, et `solver_job.perimetre`
-- des animateurs et des stands. C'est l'inventaire de
-- PorteursDIdentifiantStructurelleTest qui le dit, et c'est pour cette
-- question-là qu'il existe.

/* --------- 6. La bascule --------- */

ALTER TABLE emplacement DROP CONSTRAINT emplacement_pkey;
ALTER TABLE emplacement DROP COLUMN id;
ALTER TABLE emplacement RENAME COLUMN id_nouveau TO id;
ALTER TABLE emplacement ADD PRIMARY KEY (edition_id, id);

-- La séquence garde son nom de naissance (emplacement_id_nouveau_seq) : sans
-- conséquence, la duplication d'édition comme la resynchronisation d'après
-- restauration la retrouvent par pg_get_serial_sequence(table, colonne).

ALTER TABLE stand
    ADD CONSTRAINT stand_emplacement_fkey
    FOREIGN KEY (edition_id, emplacement_id)
    REFERENCES emplacement (edition_id, id);

-- L'index qui servait la clé étrangère suivait l'ancienne colonne.
CREATE INDEX IF NOT EXISTS stand_emplacement_idx ON stand (edition_id, emplacement_id);
